### ISSUE TITLE
Cannot invoke "org.eclipse.jetty.util.Callback.failed(java.lang.Throwable)"

### ISSUE THREAD

**Issue by rymsha** [enonic/xp#10261]
Hi. After upgrading from 7.12 to 7.13.2 I see this exception on all nodes at random times.
```
mo.e.jetty.io.AbstractConnection[0;39m -
java.lang.NullPointerException: Cannot invoke "org.eclipse.jetty.util.Callback.failed(java.lang.Throwable)" because "callback" is null
at org.eclipse.jetty.io.AbstractConnection.lambda$failedCallback$0(AbstractConnection.java:92)
at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by rymsha** [comment]
This is indeed caused by https://github.com/eclipse/jetty.project/issues/9476
