### ISSUE TITLE
Can't access content in `/archive` from JS API

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp#10304]
An attempt to fetch a content item by id from the Archive with this JS code:

```Javascript
const contentLib = require('/lib/xp/content');
const contextLib = require('/lib/xp/context');

const content = contextLib.run({
    repository: 'some.repo.name',
    attributes: {
        contentRootPath: '/archive'
    }
}, function() {
    return contentLib.get({key: contentId})
});
```

results in the following error:

```Java
Caused by: java.lang.RuntimeException: Error getting node
	at com.enonic.xp.util.Exceptions.newRuntime(Exceptions.java:33)
	at com.enonic.xp.core.impl.content.GetContentByIdCommand.execute(GetContentByIdCommand.java:39)
	at com.enonic.xp.core.impl.content.ContentServiceImpl.doGetById(ContentServiceImpl.java:509)
	at com.enonic.xp.core.impl.content.ContentServiceImpl.lambda$getById$1(ContentServiceImpl.java:497)
	at com.enonic.xp.trace.Tracer.trace(Tracer.java:128)
	at com.enonic.xp.core.impl.content.ContentServiceImpl.getById(ContentServiceImpl.java:497)
	at com.enonic.xp.lib.content.GetContentHandler.getById(GetContentHandler.java:53)
	at com.enonic.xp.lib.content.GetContentHandler.doExecute(GetContentHandler.java:32)
	at com.enonic.xp.lib.content.BaseContextHandler.execute(BaseContextHandler.java:14)
	at org.openjdk.nashorn.internal.scripts.Script$Recompilation$2809$2567A$content.L:1#get(com.enonic.app.contentstudio.plus:/lib/xp/content.js:53)
	at org.openjdk.nashorn.internal.scripts.Script$Recompilation$2864$1510$publish_report.L:1#\==\_\!43#content(com.enonic.app.contentstudio.plus:/admin/widgets/publish-report/publish-report.js:56)
	at org.openjdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:646)
	at org.openjdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:513)
	at org.openjdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:520)
	at org.openjdk.nashorn.javaadapters.java_util_concurrent_Callable.call(Unknown Source)
	at com.enonic.xp.context.ContextImpl.callWith(ContextImpl.java:100)
	at com.enonic.xp.lib.context.ContextHandlerBean.run(ContextHandlerBean.java:36)
	at org.openjdk.nashorn.internal.scripts.Script$Recompilation$2807$1299AA$context.L:1#run(com.enonic.app.contentstudio.plus:/lib/xp/context.js:51)
	at org.openjdk.nashorn.internal.scripts.Script$Recompilation$2861$1130A$publish_report.L:1#\==\_\!43(com.enonic.app.contentstudio.plus:/admin/widgets/publish-report/publish-report.js:49)
	at org.openjdk.nashorn.internal.scripts.Script$Recompilation$2860$1923A$publish_report.L:1#\==\_\!71(com.enonic.app.contentstudio.plus:/admin/widgets/publish-report/publish-report.js:73)
	at org.openjdk.nashorn.internal.scripts.Script$Recompilation$2859$254A$publish_report.L:1#\==\_\!6(com.enonic.app.contentstudio.plus:/admin/widgets/publish-report/publish-report.js:7)
	at org.openjdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:648)
	at org.openjdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:513)
	at org.openjdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:520)
	at org.openjdk.nashorn.api.scripting.ScriptObjectMirror.call(ScriptObjectMirror.java:111)
	at com.enonic.xp.script.impl.value.FunctionScriptValue.call(FunctionScriptValue.java:38)
	at com.enonic.xp.script.impl.executor.ScriptExportsImpl.executeMethod(ScriptExportsImpl.java:59)
	at com.enonic.xp.portal.impl.controller.ControllerScriptImpl.doExecute(ControllerScriptImpl.java:64)
	at com.enonic.xp.portal.impl.controller.ControllerScriptImpl.lambda$execute$1(ControllerScriptImpl.java:36)
	at com.enonic.xp.trace.Tracer.trace(Tracer.java:128)
	at com.enonic.xp.trace.Tracer.trace(Tracer.java:134)
	at com.enonic.xp.portal.impl.controller.ControllerScriptImpl.execute(ControllerScriptImpl.java:35)
	at com.enonic.xp.admin.impl.portal.WidgetHandlerWorker.execute(WidgetHandlerWorker.java:61)
	at com.enonic.xp.admin.impl.portal.WidgetHandler.doHandle(WidgetHandler.java:58)
	at com.enonic.xp.web.handler.BaseWebHandler.handle(BaseWebHandler.java:67)
	at com.enonic.xp.web.impl.handler.WebHandlerChainImpl.handle(WebHandlerChainImpl.java:28)
	at com.enonic.xp.web.handler.BaseWebHandler.handle(BaseWebHandler.java:76)
	at com.enonic.xp.web.impl.handler.WebHandlerChainImpl.handle(WebHandlerChainImpl.java:28)
	at com.enonic.xp.web.handler.BaseWebHandler.handle(BaseWebHandler.java:76)
	at com.enonic.xp.web.impl.handler.WebHandlerChainImpl.handle(WebHandlerChainImpl.java:28)
	at com.enonic.xp.portal.impl.handler.mapping.MappingHandler.handle(MappingHandler.java:50)
	at com.enonic.xp.web.impl.handler.WebHandlerChainImpl.handle(WebHandlerChainImpl.java:28)
	at com.enonic.xp.web.handler.BaseWebHandler.handle(BaseWebHandler.java:76)
	at com.enonic.xp.web.impl.handler.WebHandlerChainImpl.handle(WebHandlerChainImpl.java:28)
	at com.enonic.xp.web.handler.BaseWebHandler.handle(BaseWebHandler.java:76)
	at com.enonic.xp.web.impl.handler.WebHandlerChainImpl.handle(WebHandlerChainImpl.java:28)
	at com.enonic.xp.web.handler.BaseWebHandler.handle(BaseWebHandler.java:76)
	at com.enonic.xp.web.impl.handler.WebHandlerChainImpl.handle(WebHandlerChainImpl.java:28)
	at com.enonic.xp.web.handler.BaseWebHandler.handle(BaseWebHandler.java:76)
	at com.enonic.xp.web.impl.handler.WebHandlerChainImpl.handle(WebHandlerChainImpl.java:28)
	at com.enonic.xp.web.handler.BaseWebHandler.handle(BaseWebHandler.java:76)
	at com.enonic.xp.web.impl.handler.WebHandlerChainImpl.handle(WebHandlerChainImpl.java:28)
	at com.enonic.xp.portal.handler.BasePortalHandler.doHandle(BasePortalHandler.java:46)
	... 85 common frames omitted
Caused by: java.lang.ClassCastException: class java.lang.String cannot be cast to class com.enonic.xp.node.NodePath (java.lang.String is in module java.base of loader 'bootstrap'; com.enonic.xp.node.NodePath is in unnamed module of loader org.apache.felix.framework.BundleWiringImpl$BundleClassLoader @64ee289)
	at com.enonic.xp.core.impl.content.ContentNodeHelper.getContentRoot(ContentNodeHelper.java:107)
	at com.enonic.xp.core.impl.content.ContentNodeTranslator.doTranslate(ContentNodeTranslator.java:110)
	at com.enonic.xp.core.impl.content.ContentNodeTranslator.fromNode(ContentNodeTranslator.java:64)
	at com.enonic.xp.core.impl.content.ContentNodeTranslator.fromNode(ContentNodeTranslator.java:58)
	at com.enonic.xp.core.impl.content.GetContentByIdCommand.execute(GetContentByIdCommand.java:31)
	... 136 common frames omitted

```

**Comment by alansemenov** [comment]
Found a workaround in JS code
