### ISSUE TITLE
toolbox init-project does not resolve branch only tag

### ISSUE THREAD

**Issue by ComLock** [enonic/xp#4738]
FAIL:
```
cwe@enonic:e (DEV) $ toolbox.sh init-project -d app-grid -n com.enonic.app.grid -r starter-babel -c liveReload
Retrieving Git repository from "https://github.com/enonic/starter-babel.git" ...
Unexpected error: Ref liveReload can not be resolved
org.eclipse.jgit.api.errors.RefNotFoundException: Ref liveReload can not be resolved
	at org.eclipse.jgit.api.CheckoutCommand.call(CheckoutCommand.java:243)
	at com.enonic.xp.toolbox.app.InitAppCommand.cloneGitRepository(InitAppCommand.java:110)
	at com.enonic.xp.toolbox.app.InitAppCommand.execute(InitAppCommand.java:66)
	at com.enonic.xp.toolbox.ToolCommand.run(ToolCommand.java:13)
	at com.enonic.xp.toolbox.Main.main(Main.java:50)
```

SUCCESS:
```
cwe@enonic:e (DEV) $ toolbox.sh init-project -d app-grid -n com.enonic.app.grid -r starter-babel -c test-init-project-from-tag
Retrieving Git repository from "https://github.com/enonic/starter-babel.git" ...
Git repository retrieved.
Adapting Gradle properties file ...
Gradle properties file adapted.
```

**Comment by ComLock** [comment]
Says branch here:
https://github.com/enonic/xp-doc/blame/6.9/doc/reference/toolbox/init-project.rst#L29

**Comment by rymsha** [comment]
Enonic CLI is a rescue
