### ISSUE TITLE
Attempt to create a fragment in the page-template wizard throws an exception

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp#4768]
1. open a site, select Features in application selector
2. start to ad a new page-template, select the page controller
3. open the Page Component View and insert a Image
4. select the image and try to create a fragment
BUG: Exception is thrown:

java.lang.IllegalArgumentException: Content could not be created. Children not allowed in parent [/site1/_templates/__unnamed__]
        at com.enonic.xp.core.impl.content.CreateContentCommand.validateCreationAllowance(CreateContentCommand.java:216) ~[na:na]
        at com.enonic.xp.core.impl.content.CreateContentCommand.validateBlockingChecks(CreateContentCommand.java:121) ~[na:na]
        at com.enonic.xp.core.impl.content.CreateContentCommand.doExecute(CreateContentCommand.java:83) ~[na:na]
        at com.enonic.xp.core.impl.content.CreateContentCommand.execute(CreateContentCommand.java:78) ~[na:na]
        at com.enonic.xp.core.impl.content.ContentServiceImpl.create(ContentServiceImpl.java:234) ~[na:na]
        at com.enonic.xp.core.impl.content.page.region.CreateFragmentCommand.execute(CreateFragmentCommand.java:60) ~[na

**Comment by alansemenov** [comment]
We should not allow creating a fragment from a page template - just hide this option
