### ISSUE TITLE
ImageSelector content - errors in the console appear when selected images were moved

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp#4824]
1. Select Features and start to add ImageSelector content
2. go to 2-4 Image selector and insert two images 
3. click on any image (Edit, Remove buttons appear)
3. Dragging one of the images image onto a place  bellow the Edit and Remove buttons
4. clicking on images again 
BUG: error in the console appears:

PropertyArray.ts:119 Uncaught Error: Index out of bounds: index: 3, size: 2
    at PropertyArray.checkIndex (http://localhost:8080/admin/assets/1492070027416/common/js/_all.js:9341:27)
    at PropertyArray.set (http://localhost:8080/admin/assets/1492070027416/common/js/_all.js:9386:22)
    at http://localhost:8080/admin/assets/1492070027416/common/js/_all.js:67314:58
    at http://localhost:8080/admin/assets/1492070027416/common/js/_all.js:29495:29
    at Array.forEach (native)
    at ImageSelectorSelectedOptionsView.BaseSelectedOptionsView.notifyOptionMoved (http://localhost:8080/admin/assets/1492070027416/common/js/_all.js:29494:51)
    at http://localhost:8080/admin/assets/1492070027416/common/js/_all.js:29371:39
    at Array.forEach (native)
    at ImageSelectorSelectedOptionsView.BaseSelectedOptionsView.handleMovedOccurrence (http://localhost:8080/admin/assets/1492070027416/common/js/_all.js:29369:51)
    at ImageSelectorSelectedOptionsView.BaseSelectedOptionsView.handleDnDUpdate (http://localhost:8080/admin/assets/1492070027416/common/js/_all.js:29359:34)

![img-sel](https://cloud.githubusercontent.com/assets/3728712/25042187/ad896914-211e-11e7-9022-300de6d97d30.png)

﻿

​

**Comment by alansemenov** [comment]
I don't get errors when I move images under the buttons but I do get errors when I move them back above. In any case we should limit the allowed drop zone, it should not be possible to move the images under the buttons.
