### ISSUE TITLE
OptionSet -Error appears when an option contains occurrences of htmlArea

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp#4841]
1. start to add a OptionSet content. 2 or more options should be in the Set.
And one of the options should be with occurrences of HtmlArea for example:
option set->options->option->items->htmlArea(0:2)
2. open the option and add one more HtmlArea(see the first screenshot)
3. save the  content and click on another option.

BUG: error appears in the browser console and first option has not cleared
PropertyPath.ts:41 Uncaught Error: Path element was empty string at index: 4
    at http://localhost:8080/admin/assets/1492587651286/common/js/_all.js:8669:31
    at Array.forEach (native)
    at new PropertyPath (http://localhost:8080/admin/assets/1492587651286/common/js/_all.js:8664:26)
    at Function.PropertyPath.fromParent (http://localhost:8080/admin/assets/1492587651286/common/js/_all.js:8688:24)
    at PropertyArray.remove (http://localhost:8080/admin/assets/1492587651286/common/js/_all.js:9417:43)
    at InputOccurrences.FormItemOccurrences.removeOccurrenceView (http://localhost:8080/admin/assets/1492587651286/common/js/_all.js:37950:36)
    at InputOccurrences.FormItemOccurrences.update (http://localhost:8080/admin/assets/1492587651286/common/js/_all.js:37845:30)
    at HtmlArea.BaseInputTypeNotManagingAdd.update (http://localhost:8080/admin/assets/1492587651286/common/js/_all.js:41752:54)
    at InputView.update (http://localhost:8080/admin/assets/1492587651286/common/js/_all.js:40485:43)
    at http://localhost:8080/admin/assets/1492587651286/common/js/_all.js:40335:54
![step1](https://cloud.githubusercontent.com/assets/3728712/25174724/f0ab55a0-2500-11e7-8af5-07e69dc4034d.png)
![opt1](https://cloud.githubusercontent.com/assets/3728712/25174767/0ca462f6-2501-11e7-8446-d3842e62af97.png)

**Comment by ashklianko** [comment]
Implemented small fix, but in general need to recheck all option set handling. Seems more common issue.
