### ISSUE TITLE
'Create Issue' menu item should be disabled, if user has no 'Content Manager Administrator' role

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp#5187]
1. Add a user with only these two roles:

![image](https://user-images.githubusercontent.com/11612490/27480286-9fa7e5b6-5817-11e7-8155-57d5b81eb61f.png)

2. Log in with this user
3. Select content in the grid
4. Expand the Publish menu button and select "Create Issue"
5. Fill out the form fields and try to create a new issue

If user is not "Content Manager Administrator" or "Administrator", he's not allowed to create content in the root. Since we create issues in the root, user will get an error (see below).

We should check permissions and if user is not a super admin and is neither "Content Manager Administrator" or "Administrator", hide the following:

* "New Issue" button in the issue list dialog
* "Create Issue..." action in the Publish menu button's dropdown (both the grid and the wizard)
* "Create Issue" in the Publish menu dropdown in the Publish Content dialog

 Access denied to [/issues] for [CREATE] by user [user:system:user20637850] ''user20637850''
        at com.enonic.xp.repo.impl.node.NodePermissionsResolver.doRequireContextUserPermission(NodePermissionsResolver.java:43)
        at com.enonic.xp.repo.impl.node.NodePermissionsResolver.requireContextUserPermission(NodePermissionsResolver.java:18)
        at com.enonic.xp.repo.impl.node.CreateNodeCommand.execute(CreateNodeCommand.java:74)
        at com.enonic.xp.repo.impl.node.NodeServiceImpl.doCreate(NodeServiceImpl.java:236)
        at com.enonic.xp.repo.impl.node.NodeServiceImpl.create(NodeServiceImpl.java:224)
        at com.enonic.xp.core.impl.issue.CreateIssueCommand.doExecute(CreateIssueCommand.java:60)
        at com.enonic.xp.core.impl.issue.CreateIssueCommand.execute(CreateIssueCommand.java:44)
        at com.enonic.xp.core.impl.issue.IssueServiceImpl.create(IssueServiceImpl.java:41)
        at com.enonic.xp.admin.impl.rest.resource.issue.IssueResource.create(IssueResource.java:67)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:137)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:296)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:250)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:237)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:356)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:179)
        at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:220)
        at com.enonic.xp.jaxrs.impl.JaxRsServlet.service(JaxRsServlet.java:46)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at com.enonic.xp.web.impl.dispatch.mapping.ServletDefinitionImpl.service(ServletDefinitionImpl.java:39)
        at com.enonic.xp.web.impl.dispatch.pipeline.ServletPipelineImpl.service(ServletPipelineImpl.java:30)
        at com.enonic.xp.web.impl.dispatch.pipeline.FilterChainImpl.doFilter(FilterChainImpl.java:45)
        at com.enonic.xp.web.impl.dispatch.pipeline.FilterChainImpl.doFilter(FilterChainImpl.java:36)
        at com.enonic.xp.portal.impl.auth.AuthFilter.doHandle(AuthFilter.java:45)
        at com.enonic.xp.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:31)
        at com.enonic.xp.web.filter.BaseWebFilter.doFilter(BaseWebFilter.java:33)
        at com.enonic.xp.web.impl.dispatch.mapping.FilterDefinitionImpl.doFilter(FilterDefinitionImpl.java:40)
        at com.enonic.xp.web.impl.dispatch.pipeline.FilterChainImpl.doFilter(FilterChainImpl.java:50)
        at com.enonic.xp.web.impl.dispatch.pipeline.FilterChainImpl.doFilter(FilterChainImpl.java:36)
        at com.enonic.xp.web.impl.auth.BasicAuthFilter.doHandle(BasicAuthFilter.java:33)
        at com.enonic.xp.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:31)
        at com.enonic.xp.web.filter.BaseWebFilter.doFilter(BaseWebFilter.java:33)
        at com.enonic.xp.web.impl.dispatch.mapping.FilterDefinitionImpl.doFilter(FilterDefinitionImpl.java:40)
        at com.enonic.xp.web.impl.dispatch.pipeline.FilterChainImpl.doFilter(FilterChainImpl.java:50)
        at com.enonic.xp.web.impl.dispatch.pipeline.FilterChainImpl.doFilter(FilterChainImpl.java:36)
        at com.enonic.xp.web.impl.context.ContextFilter.lambda$doHandle$0(ContextFilter.java:33)
        at com.enonic.xp.context.ContextImpl.callWith(ContextImpl.java:101)
        at com.enonic.xp.web.impl.context.ContextFilter.doHandle(ContextFilter.java:32)
        at com.enonic.xp.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:31)
        at com.enonic.xp.web.filter.BaseWebFilter.doFilter(BaseWebFilter.java:33)
        at com.enonic.xp.web.impl.dispatch.mapping.FilterDefinitionImpl.doFilter(FilterDefinitionImpl.java:40)
        at com.enonic.xp.web.impl.dispatch.pipeline.FilterChainImpl.doFilter(FilterChainImpl.java:50)
        at com.enonic.xp.web.impl.dispatch.pipeline.FilterChainImpl.doFilter(FilterChainImpl.java:36)
        at com.enonic.xp.web.vhost.impl.VirtualHostFilter.doHandle(VirtualHostFilter.java:57)
        at com.enonic.xp.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:31)
        at com.enonic.xp.web.filter.BaseWebFilter.doFilter(BaseWebFilter.java:33)
        at com.enonic.xp.web.impl.dispatch.mapping.FilterDefinitionImpl.doFilter(FilterDefinitionImpl.java:40)
        at com.enonic.xp.web.impl.dispatch.pipeline.FilterChainImpl.doFilter(FilterChainImpl.java:50)
![access-d](https://user-images.githubusercontent.com/3728712/27479841-47836f8e-581e-11e7-839c-e64bab326e58.png)

**Comment by ashklianko** [comment]
@ase, aren't we supposed to let user do create issue in that case?

**Comment by alansemenov** [comment]
Well, the problem is that "issues" node is in the root of the repo and users without admin role are not allowed to create new content in the root. See also #5188. I'm not aware what this limitation is caused by, maybe @runarmyklebust knows?

**Comment by alansemenov** [comment]
@ashklianko Wait with this one, we'll ask @tsi.

**Comment by alansemenov** [comment]
We'll fix permissions instead, see #5238
