### ISSUE TITLE
'New' button should be disabled when nothing is selected in the grid and user is not allowed to create content in the root

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp#5188]
1. Add a user with only these two roles:

![image](https://user-images.githubusercontent.com/11612490/27480286-9fa7e5b6-5817-11e7-8155-57d5b81eb61f.png)

2. Log in with this user
3. Click "New" button
4. Select content type

1)If user is not "Content Manager Administrator" or "Administrator", he's not allowed to create content in the root, so we should disable the "New" action in the toolbar.
2)The same exception thrown when the User tries to move a content to the root directory

BUG: 
expected: 'New' button should be disabled if user doesn't have proper rights to create content in the root
Actual: when New has been pressed and Folder selected,  exception thrown:
om.enonic.xp.content.ContentAccessException: Access denied to [/] for [CREATE] by user [user:system:user20637850] 'user20637850'
        at com.enonic.xp.core.impl.content.CreateContentCommand.doExecute(CreateContentCommand.java:115)
        at com.enonic.xp.core.impl.content.CreateContentCommand.execute(CreateContentCommand.java:80)
        at com.enonic.xp.core.impl.content.ContentServiceImpl.create(ContentServiceImpl.java:227)
        at com.enonic.xp.admin.impl.rest.resource.content.ContentResource.create(ContentResource.java:243)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:137)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:296)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:250)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:237)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:356)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:179)
        at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:220)
        at com.enonic.xp.jaxrs.impl.JaxRsServlet.service(JaxRsServlet.java:46)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at com.enonic.xp.web.impl.dispatch.mapping.ServletDefinitionImpl.service(ServletDefinitionImpl.java:39)
        at com.enonic.xp.web.impl.dispatch.pipeline.ServletPipelineImpl.service(ServletPipelineImpl.java:30)
        at com.enonic.xp.web.impl.dispatch.pipeline.FilterChainImpl.doFilter(FilterChainImpl.java:45)
        at com.enonic.xp.web.impl.dispatch.pipeline.FilterChainImpl.doFilter(FilterChainImpl.java:36)
        at com.enonic.xp.portal.impl.auth.AuthFilter.doHandle(AuthFilter.java:45)
        at com.enonic.xp.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:31)
        at com.enonic.xp.web.filter.BaseWebFilter.doFilter(BaseWebFilter.java:33)
        at com.enonic.xp.web.impl.dispatch.mapping.FilterDefinitionImpl.doFilter(FilterDefinitionImpl.java:40)
        at com.enonic.xp.web.impl.dispatch.pipeline.FilterChainImpl.doFilter(FilterChainImpl.java:50)
        at com.enonic.xp.web.impl.dispatch.pipeline.FilterChainImpl.doFilter(FilterChainImpl.java:36)
        at com.enonic.xp.web.impl.auth.BasicAuthFilter.doHandle(BasicAuthFilter.java:33)
        at com.enonic.xp.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:31)
        at com.enonic.xp.web.filter.BaseWebFilter.doFilter(BaseWebFilter.java:33)
        at com.enonic.xp.web.impl.dispatch.mapping.FilterDefinitionImpl.doFilter(FilterDefinitionImpl.java:40)
        at com.enonic.xp.web.impl.dispatch.pipeline.FilterChainImpl.doFilter(FilterChainImpl.java:50)
        at com.enonic.xp.web.impl.dispatch.pipeline.FilterChainImpl.doFilter(FilterChainImpl.java:36)
        at com.enonic.xp.web.impl.context.ContextFilter.lambda$doHandle$0(ContextFilter.java:33)
        at com.enonic.xp.context.ContextImpl.callWith(ContextImpl.java:101)
        at com.enonic.xp.web.impl.context.ContextFilter.doHandle(ContextFilter.java:32)
        at com.enonic.xp.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:31)

![root-f](https://user-images.githubusercontent.com/3728712/27480072-40b82a4a-581f-11e7-976d-7020d767d8f1.png)

**Comment by ashklianko** [comment]
I have to note that 'New' action for such a user in the root is enabled only after login, if you select/unselect any content then it is correctly disabled.

**Comment by alansemenov** [comment]
Then it's definitely a bug :)

**Comment by ashklianko** [comment]
Noted just in case Slava or Mikita take it first :)
