### ISSUE TITLE
ResponseSerializer - ArithmeticException for big byte sources

### ISSUE THREAD

**Issue by GlennRicaud** [enonic/xp#5528]
*When downloading a dump (size is over 2GB), an ArithmeticException is thrown.
  * Look at the response.setContentLength in ResponseSerializer
  * Use the setContentLengthLong for the writeToStream of ByteSource

* Investigate/Modify/Test
Support ticket: https://enonic.zendesk.com/agent/tickets/2097

```
;Caused by: java.lang.ArithmeticException: integer overflow 
>	at java.lang.Math.toIntExact(Math.java:1011) ~[na:1.8.0_131] 
m	at com.enonic.xp.web.impl.serializer.ResponseSerializer.writeToStream(ResponseSerializer.java:132) ~[na:na] 
m	at com.enonic.xp.web.impl.serializer.ResponseSerializer.serializeBody(ResponseSerializer.java:103) ~[na:na] 
l	at com.enonic.xp.web.impl.serializer.ResponseSerializer.serializeBody(ResponseSerializer.java:66) ~[na:na] 
h	at com.enonic.xp.web.impl.serializer.ResponseSerializer.serialize(ResponseSerializer.java:44) ~[na:na] 
?	at com.enonic.xp.web.impl.serializer.ResponseSerializationServiceImpl.serialize(ResponseSerializationServiceImpl.java:21) ~[na:na] 
g	at com.enonic.xp.web.impl.handler.WebDispatcherServlet.service(WebDispatcherServlet.java:71) ~[na:na] 
`	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) ~[web-jetty-6.10.3.jar:6.10.3] 
r	at com.enonic.xp.web.impl.dispatch.mapping.ServletDefinitionImpl.service(ServletDefinitionImpl.java:39) ~[na:na] 
o	at com.enonic.xp.web.impl.dispatch.pipeline.ServletPipelineImpl.service(ServletPipelineImpl.java:30) ~[na:na] 
h	at com.enonic.xp.web.impl.dispatch.pipeline.FilterChainImpl.doFilter(FilterChainImpl.java:45) ~[na:na] 
h	at com.enonic.xp.web.impl.dispatch.pipeline.FilterChainImpl.doFilter(FilterChainImpl.java:36) ~[na:na] 
T	at com.enonic.xp.portal.impl.auth.AuthFilter.doHandle(AuthFilter.java:45) ~[na:na] 
b	at com.enonic.xp.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:31) ~[na:na] 
T	at com.enonic.xp.web.filter.BaseWebFilter.doFilter(BaseWebFilter.java:33) ~[na:na] 
... 78 common frames omitted;Caused by: java.lang.ArithmeticException: integer overflow 
>	at java.lang.Math.toIntExact(Math.java:1011) ~[na:1.8.0_131] 
m	at com.enonic.xp.web.impl.serializer.ResponseSerializer.writeToStream(ResponseSerializer.java:132) ~[na:na] 
m	at com.enonic.xp.web.impl.serializer.ResponseSerializer.serializeBody(ResponseSerializer.java:103) ~[na:na] 
l	at com.enonic.xp.web.impl.serializer.ResponseSerializer.serializeBody(ResponseSerializer.java:66) ~[na:na] 
h	at com.enonic.xp.web.impl.serializer.ResponseSerializer.serialize(ResponseSerializer.java:44) ~[na:na] 
?	at com.enonic.xp.web.impl.serializer.ResponseSerializationServiceImpl.serialize(ResponseSerializationServiceImpl.java:21) ~[na:na] 
g	at com.enonic.xp.web.impl.handler.WebDispatcherServlet.service(WebDispatcherServlet.java:71) ~[na:na] 
`	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) ~[web-jetty-6.10.3.jar:6.10.3] 
r	at com.enonic.xp.web.impl.dispatch.mapping.ServletDefinitionImpl.service(ServletDefinitionImpl.java:39) ~[na:na] 
o	at com.enonic.xp.web.impl.dispatch.pipeline.ServletPipelineImpl.service(ServletPipelineImpl.java:30) ~[na:na] 
h	at com.enonic.xp.web.impl.dispatch.pipeline.FilterChainImpl.doFilter(FilterChainImpl.java:45) ~[na:na] 
h	at com.enonic.xp.web.impl.dispatch.pipeline.FilterChainImpl.doFilter(FilterChainImpl.java:36) ~[na:na] 
T	at com.enonic.xp.portal.impl.auth.AuthFilter.doHandle(AuthFilter.java:45) ~[na:na] 
b	at com.enonic.xp.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:31) ~[na:na] 
T	at com.enonic.xp.web.filter.BaseWebFilter.doFilter(BaseWebFilter.java:33) ~[na:na] 
... 78 common frames omitted
```

**Comment by GlennRicaud** [comment]
For myself: Create PR for master
