### ISSUE TITLE
Invalid input type for AttachmentUpload

### ISSUE THREAD

**Issue by aro** [enonic/xp#5776]
Steps to reproduce issue:
- create a content type with an AttachmentUpload field
- create a content of the type
- in the AU field, upload a file with a name containing spaces 
- trying to modify this content using `contentLib.modify` will always fail with an exception

The problem is that `AttachmentUploaderType` uses `Reference` as underlying type. When trying to convert from the JavaScript string type to a `Reference` it fails because a `Reference` is a wrapper for a `NodeId`, and `NodeId` allows a limited set of characters.

Is it correct that `AttachmentUpload` is based on a `Reference`? Shouldn't it have been `BinaryReference`?

This was reported in Discuss: 
https://discuss.enonic.com/t/unable-to-edit-object-with-attachment-with-content-modify/1285

Stack trace:
```
Caused by: com.enonic.xp.data.ValueTypeException: Value of type [java.lang.String] cannot be converted to [Reference]: NodeId format incorrect: Screenshot from 2017-10-03 15-29-40.png
	at com.enonic.xp.data.ValueType.convertError(ValueType.java:92)
	at com.enonic.xp.data.ValueType.convert(ValueType.java:74)
	at com.enonic.xp.data.Value.asReference(Value.java:193)
	at com.enonic.xp.inputtype.AttachmentUploaderType.createValue(AttachmentUploaderType.java:21)
	at com.enonic.xp.lib.common.FormJsonToPropertyTreeTranslator.mapValue(FormJsonToPropertyTreeTranslator.java:96)
	at com.enonic.xp.lib.common.FormJsonToPropertyTreeTranslator.addValue(FormJsonToPropertyTreeTranslator.java:74)
	at com.enonic.xp.lib.common.FormJsonToPropertyTreeTranslator.lambda$addValue$0(FormJsonToPropertyTreeTranslator.java:70)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at com.enonic.xp.lib.common.FormJsonToPropertyTreeTranslator.addValue(FormJsonToPropertyTreeTranslator.java:70)
	at com.enonic.xp.lib.common.FormJsonToPropertyTreeTranslator.traverse(FormJsonToPropertyTreeTranslator.java:54)
	at com.enonic.xp.lib.common.FormJsonToPropertyTreeTranslator.translate(FormJsonToPropertyTreeTranslator.java:43)
	at com.enonic.xp.lib.content.BaseContextHandler.translateToPropertyTree(BaseContextHandler.java:76)
	at com.enonic.xp.lib.content.ModifyContentHandler.createPropertyTree(ModifyContentHandler.java:157)
	at com.enonic.xp.lib.content.ModifyContentHandler.updateContent(ModifyContentHandler.java:103)
	at com.enonic.xp.lib.content.ModifyContentHandler.lambda$newContentEditor$0(ModifyContentHandler.java:81)
```

**Comment by aro** [comment]
Hi @navyhod 
The issue has been fixed and it will be included in 6.13 release.
It's available in the latest snapshot from XP, in the master branch. But that is not stable, and must not be used in production.
