### ISSUE TITLE
Issue when restoring a snapshot - cluster state RED

### ISSUE THREAD

**Issue by runarmyklebust** [enonic/xp#5862]
2017-12-12 08:00:40,483 INFO  org.elasticsearch.cluster.metadata - [local-node] closing indices      [[search-system-repo]]
    2017-12-12 08:00:40,493 INFO  c.e.x.r.i.e.s.AbstractSnapshotExecutor - Closed index search-system-repo
    2017-12-12 08:00:40,493 INFO  org.elasticsearch.cluster.metadata - [local-node] closing indices [[storage-system-repo]]
    2017-12-12 08:00:40,499 INFO  c.e.x.r.i.e.s.AbstractSnapshotExecutor - Closed index storage-system-repo
    2017-12-12 08:00:40,551 WARN  org.elasticsearch.cluster.metadata - [local-node] [search-system-repo] re-syncing mappings with cluster state for types [[_default_]]
        2017-12-12 08:00:40,764 INFO  org.elasticsearch.snapshots - [local-node] restore [enonic-xp-snapshot-repo:vif-full-22] is done
    2017-12-12 08:00:40,771 INFO  c.e.x.r.i.e.s.AbstractSnapshotExecutor - Opened index search-system-repo
    2017-12-12 08:00:40,771 INFO  c.e.x.r.i.e.s.AbstractSnapshotExecutor - Opened index storage-system-repo
    2017-12-12 08:00:40,782 INFO  org.elasticsearch.cluster.metadata - [local-node] closing indices [[search-cms-repo]]
    2017-12-12 08:00:40,788 INFO  c.e.x.r.i.e.s.AbstractSnapshotExecutor - Closed index search-cms-repo
    2017-12-12 08:00:40,789 INFO  org.elasticsearch.cluster.metadata - [local-node] closing indices [[storage-cms-repo]]
    2017-12-12 08:00:40,793 INFO  c.e.x.r.i.e.s.AbstractSnapshotExecutor - Closed index storage-cms-repo
    2017-12-12 08:00:45,931 ERROR c.e.x.e.impl.ClientActivator - Cluster health in state 'RED'
    2017-12-12 08:00:45,991 INFO  c.e.x.e.impl.ClientActivator - Cluster not operational, unregister elasticsearch-client
    2017-12-12 08:00:51,484 ERROR c.e.x.r.i.r.NodeRepositoryServiceImpl - Cluster not healthy: timed out: true, state: RED
    2017-12-12 08:00:51,487 ERROR c.e.x.p.i.e.ExceptionRendererImpl - Unable to initialize repositories
    com.enonic.xp.web.WebException: Unable to initialize repositories
    at com.enonic.xp.web.impl.exception.ExceptionMapperImpl.map(ExceptionMapperImpl.java:32)
    at com.enonic.xp.web.impl.handler.WebDispatcherServlet.handleError(WebDispatcherServlet.java:146)
    at com.enonic.xp.web.impl.handler.WebDispatcherServlet.doHandle(WebDispatcherServlet.java:140)
    at com.enonic.xp.web.impl.handler.WebDispatcherServlet.service(WebDispatcherServlet.java:63)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
    at com.enonic.xp.web.impl.dispatch.mapping.ServletDefinitionImpl.service(ServletDe

**Comment by runarmyklebust** [comment]
This is just temporary RED cluster state while the snapshot is restored.
