### ISSUE TITLE
Initialization on non-master nodes

### ISSUE THREAD

**Issue by GlennRicaud** [enonic/xp#6255]
With a clean cluster configured with 3 nodes (6.14.3):

- Start first node
  - The node waits or is in RED state
- Starts the second node
  - Multiple exceptions when starting:
```
com.enonic.xp.repository.RepositoryNotFoundException: Repository with id [system-repo] not found
	at com.enonic.xp.repo.impl.node.NodeServiceImpl.lambda$verifyBranchExists$10(NodeServiceImpl.java:982)
	at com.enonic.xp.context.ContextImpl.runWith(ContextImpl.java:85)
	at com.enonic.xp.repo.impl.node.NodeHelper.runAsAdmin(NodeHelper.java:15)
	at com.enonic.xp.repo.impl.node.NodeServiceImpl.verifyBranchExists(NodeServiceImpl.java:976)
	at com.enonic.xp.repo.impl.node.NodeServiceImpl.verifyContext(NodeServiceImpl.java:958)
	at com.enonic.xp.repo.impl.node.NodeServiceImpl.refresh(NodeServiceImpl.java:711)
	at com.enonic.xp.core.impl.app.ApplicationRepoServiceImpl.getApplications(ApplicationRepoServiceImpl.java:90)
	at com.enonic.xp.core.impl.app.ApplicationServiceImpl.doInstallStoredApplications(ApplicationServiceImpl.java:201)
```

Visually, this has, for example, as a result that the IssueService is not started (->ContentServiceImpl->ContentTypeServiceImpl->ApplicationServiceImpl):
![Screen Shot 2018-05-15 at 15.41.52.png](https://images.zenhubusercontent.com/58a5657151aa2c3057749a34/e4258cb3-6b49-42c6-9b77-56e89c848b73)

**Comment by GlennRicaud** [comment]
Also noticed that IssueService does not check that it is the master node (Not the problem here, but should be fixed)

**Comment by GlennRicaud** [comment]
=> Initialization of services on non-master nodes should be blocking until the end of the Initializer procedure on the master node...
