### ISSUE TITLE
java.lang.IllegalStateException: STREAM

### ISSUE THREAD

**Issue by GlennRicaud** [enonic/xp#6273]
For a cluster configured for 3 nodes but 2 nodes down.
When checking /status/cluster.manager:

=> Caused by: java.lang.IllegalStateException: STREAM
	at org.eclipse.jetty.server.Response.getWriter(Response.java:931)
	at javax.servlet.ServletResponseWrapper.getWriter(ServletResponseWrapper.java:152)
	at com.enonic.xp.portal.impl.auth.AuthResponseWrapper.getWriter(AuthResponseWrapper.java:59)
	at com.enonic.xp.server.impl.status.StatusServlet.serializeJson(StatusServlet.java:120)
	at com.enonic.xp.server.impl.status.StatusServlet.serializeError(StatusServlet.java:132)
	at com.enonic.xp.server.impl.status.StatusServlet.reportFromReporter(StatusServlet.java:98)
	at com.enonic.xp.server.impl.status.StatusServlet.doGet(StatusServlet.java:69)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at com.enonic.xp.web.impl.dispatch.mapping.ServletDefinitionImpl.service(ServletDefinitionImpl.java:39)
	at com.enonic.xp.web.impl.dispatch.pipeline.ServletPipelineImpl.service(ServletPipelineImpl.java:30)
	at com.enonic.xp.web.impl.dispatch.pipeline.FilterChainImpl.doFilter(FilterChainImpl.java:45)
	at com.enonic.xp.web.impl.dispatch.pipeline.FilterChainImpl.doFilter(FilterChainImpl.java:36)
	at com.enonic.xp.portal.impl.auth.AuthFilter.doHandle(AuthFilter.java:45)
	at com.enonic.xp.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:31)
	at com.enonic.xp.web.filter.BaseWebFilter.doFilter(BaseWebFilter.java:33)
	... 61 more

**Comment by GlennRicaud** [comment]
ElasticSearch exception are not caught. Implement a mechanism similar to ClientActivator before:
* Modify com.enonic.xp.cluster.ClusterHealth to have error messages
* Catch the exception in ElasticsearchCluster::getHealth, add the error messages and set a status RED.
=> This will fix the inactivation of clusters in ClusterManagerImpl, not working as intended today.

**Comment by GlennRicaud** [comment]
Done. The deactivation works properly now:
```
2018-05-30 12:04:36,415 ERROR c.e.x.c.impl.ClusterManagerImpl - Provider elasticsearch not healthy
2018-05-30 12:04:36,415 INFO  c.e.x.c.impl.ClusterManagerImpl - Deactivating all providers
```

Problem visible now: The status servlet is not up anymore when the cluster is disabled. Fix this in another issue.

**Comment by GlennRicaud** [comment]
We lose here the information from the ES exceptions:
* Add a throwable in com.enonic.xp.cluster.ClusterHealth similar to the errorMessages in com.enonic.xp.elasticsearch.impl.status.cluster.ClusterHealth
* Modify HealthValidator and ClusterHealthError to log these errors
