### ISSUE TITLE
Java env proxy fails in dev mode

### ISSUE THREAD

**Issue by ComLock** [enonic/xp#6505]
You can setup a lot of environment variables for proxy.

Java will probably ignore these:

- http_proxy
- https_proxy
- HTTP_PROXY
- HTTPS_PROXY
- no_proxy

But might use these:

- JAVA_OPTS
- DEFAULT_JVM_OPTS

Which are typically setup like:

```
-Dhttp.proxyHost=SNIP -Dhttps.proxyHost=SNIP -Dhttp.proxyPort=SNIP -Dhttps.proxyPort=SNIP -Dhttp.proxyUser=SNIP -Dhttps.proxyUser=SNIP -Dhttp.proxyPassword=SNIP -Dhttps.proxyPassword=SNIP -Dhttp.nonProxyHosts=SNIP -Dhttps.nonProxyHosts=SNIP
```

Now, this works fine, even with authenticated proxy when you are running XP in normal mode.
In DEV mode I get this error:

```
2018-08-16 14:05:04,789 INFO  c.e.x.c.i.app.ApplicationServiceImpl - Application [com.enonic.app.test.lib.git] installed successfully
Exception in thread "pool-38-thread-1" java.lang.NoClassDefFoundError: org/eclipse/jgit/transport/SshSessionFactory
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at com.enonic.xp.script.impl.bean.ScriptBeanFactoryImpl.newBean(ScriptBeanFactoryImpl.java:23)
	at com.enonic.xp.script.impl.function.ScriptFunctions.newBean(ScriptFunctions.java:68)
	at jdk.nashorn.internal.scripts.Script$Recompilation$243$1375AAA$main.L:1#L:1-3(com.enonic.app.test.lib.git:/main.js:1)
	at jdk.nashorn.internal.scripts.Script$Recompilation$241$139I$main.L:1#L:1-1#n(com.enonic.app.test.lib.git:/main.js:1)
	at jdk.nashorn.internal.scripts.Script$Recompilation$242$1038AAA$main.L:1#L:1-2(com.enonic.app.test.lib.git:/main.js:1)
	at jdk.nashorn.internal.scripts.Script$Recompilation$241$139I$main.L:1#L:1-1#n(com.enonic.app.test.lib.git:/main.js:1)
	at jdk.nashorn.internal.scripts.Script$Recompilation$240$116A$main.:scopeCall(com.enonic.app.test.lib.git:/main.js)
	at jdk.nashorn.internal.scripts.Script$Recompilation$240$116A$main.L:1#L:1-1(com.enonic.app.test.lib.git:/main.js:1)
	at jdk.nashorn.internal.scripts.Script$Recompilation$239$54AAAAAA$main.L:1(com.enonic.app.test.lib.git:/main.js:1)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:649)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
	at jdk.nashorn.api.scripting.ScriptObjectMirror.call(ScriptObjectMirror.java:117)
	at com.enonic.xp.script.impl.executor.ScriptExecutorImpl.executeRequire(ScriptExecutorImpl.java:218)
	at com.enonic.xp.script.impl.executor.ScriptExecutorImpl.requireJs(ScriptExecutorImpl.java:268)
	at com.enonic.xp.script.impl.executor.ScriptExecutorImpl.requireJsOrJson(ScriptExecutorImpl.java:282)
	at com.enonic.xp.script.impl.executor.ScriptExecutorImpl.executeRequire(ScriptExecutorImpl.java:177)
	at com.enonic.xp.script.impl.executor.ScriptExecutorImpl.executeMain(ScriptExecutorImpl.java:129)
	at com.enonic.xp.script.impl.standard.ScriptRuntimeImpl.execute(ScriptRuntimeImpl.java:34)
	at com.enonic.xp.portal.impl.script.PortalScriptServiceImpl.execute(PortalScriptServiceImpl.java:53)
	at com.enonic.xp.portal.impl.main.MainExecutor.executeMain(MainExecutor.java:63)
	at com.enonic.xp.portal.impl.main.MainExecutor.started(MainExecutor.java:51)
	at com.enonic.xp.portal.impl.main.MainExecutor.started(MainExecutor.java:46)
	at com.enonic.xp.portal.impl.main.MainExecutor.onEvent(MainExecutor.java:40)
	at com.enonic.xp.core.impl.event.EventMulticaster.publish(EventMulticaster.java:51)
	at com.enonic.xp.core.impl.event.EventMulticaster.publish(EventMulticaster.java:43)
	at com.enonic.xp.core.impl.event.EventPublisherImpl.lambda$dispatchEvent$0(EventPublisherImpl.java:66)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.eclipse.jgit.transport.SshSessionFactory not found by com.enonic.app.test.lib.git [120]
	at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1558)
	at org.apache.felix.framework.BundleWiringImpl.access$400(BundleWiringImpl.java:79)
	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:1998)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 32 more
```

**Comment by rymsha** [comment]
jgit uses Java ServiceLoader mechanics. It is problematic on JVM. #8361 hopefully will help.
Currently your app/lib has to deal with it via `SshSessionFactory.setInstance(...)`
