### ISSUE TITLE
Error when rolling back to version of content with x-data that contains Image Selector

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp#6538]
1. Configure x-data with image selector 
2. specify in the x-data allowContentType>base:folder</allowContentType
3. Deploy  the application
4. Add a site, then open new folder-wizard
5. Select 2-3 images in  x-data form, save the content
6. Open Versions widget in the wizard
7. roll back the previous version

Error in console: 
`_all.js:19536 Uncaught Error: Invalid content id: 
    at new ContentId (http://localhost:8080/admin/tool/com.enonic.xp.app.contentstudio/main/_/asset/com.enonic.xp.app.contentstudio:1536048481/admin/common/js/_all.js:1:1355160)
    at http://localhost:8080/admin/tool/com.enonic.xp.app.contentstudio/main/_/asset/com.enonic.xp.app.contentstudio:1536048481/admin/common/js/_all.js:1:1441307
    at Array.map (<anonymous>)
    at ImageOptionDataLoader.sendPreLoadRequest (http://localhost:8080/admin/tool/com.enonic.xp.app.contentstudio/main/_/asset/com.enonic.xp.app.contentstudio:1536048481/admin/common/js/_all.js:1:1441283)
    at ImageOptionDataLoader.BaseLoader.preLoad (`

 
![image](https://user-images.githubusercontent.com/3728712/45024763-65f9cd00-b042-11e8-93ac-e9702896013c.png)

**Comment by sgauruseu** [comment]
I checked this issue on new build. Issue does not reproduce
