### ISSUE TITLE
Repository caching - Race condition?

### ISSUE THREAD

**Issue by GlennRicaud** [enonic/xp#6681]
After the start of a cluster, I got the following everytime I tried to login on non master node:
```
12:50:44.715 ERROR c.e.x.p.i.e.ExceptionRendererImpl - Branch with id [draft] not found
com.enonic.xp.web.WebException: Branch with id [draft] not found
	at com.enonic.xp.web.impl.exception.ExceptionMapperImpl.map(ExceptionMapperImpl.java:32)
	at com.enonic.xp.portal.handler.BasePortalHandler.handleError(BasePortalHandler.java:62)
	at com.enonic.xp.portal.handler.BasePortalHandler.doHandle(BasePortalHandler.java:54)
	at com.enonic.xp.web.handler.BaseWebHandler.handle(BaseWebHandler.java:66)
	at com.enonic.xp.web.impl.handler.WebHandlerChainImpl.handle(WebHandlerChainImpl.java:30)
	at com.enonic.xp.web.impl.trace.TraceWebFilter.doHandle(TraceWebFilter.java:38)
	at com.enonic.xp.web.handler.BaseWebHandler.handle(BaseWebHandler.java:66)
	at com.enonic.xp.web.impl.handler.WebHandlerChainImpl.handle(WebHandlerChainImpl.java:30)
	at com.enonic.xp.web.impl.handler.WebDispatcherImpl.dispatch(WebDispatcherImpl.java:50)
	at com.enonic.xp.web.impl.handler.WebDispatcherServlet.doHandle(WebDispatcherServlet.java:135)
	at com.enonic.xp.web.impl.handler.WebDispatcherServlet.service(WebDispatcherServlet.java:63)
```

Best guess: There is a problem with the invalidation of the repository map.
- Confirm that this is the problem and find a robust solution

**Comment by rymsha** [comment]
This happens because `isInitialized()` methods are not symmetric with `doInitializaze()`. And similar bugs exist in most initializers.

For instance, `ContentInitializer` returns isInitialized() = true` when `/content` node exists in master branch, but `doInitialize`, after creating `/content` in master also pushes it to draft branch and finally "refreshes" (persists) the data.
