### ISSUE TITLE
Growing number of logback-threads

### ISSUE THREAD

**Issue by runarmyklebust** [enonic/xp#6814]
We have seen, on customer installations, a very large amount of logback-threads (like 2K threads, all in state waiting)

Is it possible that e.g if doing concurrent logging, that new threads will be spawned and never cleaned up?

Some research here to try to recreate issue would be cool.

**Comment by rymsha** [comment]
most likely fixed by #7555

**Comment by rymsha** [comment]
God a thread dump that shows the problem

It is not obvious, but threads are grouped by 8 in separate thread pools (it is visible from what they are waiting on)

Here is a snippet: `waiting on <0x579f0c03>` and ` waiting on <0x692c1df1>`

```
logback-16 id=296143 state=WAITING
    - waiting on <0x579f0c03> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
    - locked <0x579f0c03> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
    at java.base@11.0.5/jdk.internal.misc.Unsafe.park(Native Method)
    at java.base@11.0.5/java.util.concurrent.locks.LockSupport.park(Unknown Source)
    at java.base@11.0.5/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source)
    at java.base@11.0.5/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(Unknown Source)
    at java.base@11.0.5/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(Unknown Source)
    at java.base@11.0.5/java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
    at java.base@11.0.5/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.base@11.0.5/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.base@11.0.5/java.lang.Thread.run(Unknown Source)

logback-15 id=296137 state=WAITING
    - waiting on <0x579f0c03> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
    - locked <0x579f0c03> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
    at java.base@11.0.5/jdk.internal.misc.Unsafe.park(Native Method)
    at java.base@11.0.5/java.util.concurrent.locks.LockSupport.park(Unknown Source)
    at java.base@11.0.5/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source)
    at java.base@11.0.5/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(Unknown Source)
    at java.base@11.0.5/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(Unknown Source)
    at java.base@11.0.5/java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
    at java.base@11.0.5/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.base@11.0.5/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.base@11.0.5/java.lang.Thread.run(Unknown Source)

logback-14 id=296130 state=WAITING
    - waiting on <0x579f0c03> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
    - locked <0x579f0c03> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
    at java.base@11.0.5/jdk.internal.misc.Unsafe.park(Native Method)
    at java.base@11.0.5/java.util.concurrent.locks.LockSupport.park(Unknown Source)
    at java.base@11.0.5/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source)
    at java.base@11.0.5/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(Unknown Source)
    at java.base@11.0.5/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(Unknown Source)
    at java.base@11.0.5/java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
    at java.base@11.0.5/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.base@11.0.5/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.base@11.0.5/java.lang.Thread.run(Unknown Source)

logback-13 id=296125 state=WAITING
    - waiting on <0x579f0c03> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
    - locked <0x579f0c03> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
    at java.base@11.0.5/jdk.internal.misc.Unsafe.park(Native Method)
    at java.base@11.0.5/java.util.concurrent.locks.LockSupport.park(Unknown Source)
    at java.base@11.0.5/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source)
    at java.base@11.0.5/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(Unknown Source)
    at java.base@11.0.5/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(Unknown Source)
    at java.base@11.0.5/java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
    at java.base@11.0.5/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.base@11.0.5/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.base@11.0.5/java.lang.Thread.run(Unknown Source)

logback-12 id=296096 state=TIMED_WAITING
    - waiting on <0x579f0c03> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
    - locked <0x579f0c03> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
    at java.base@11.0.5/jdk.internal.misc.Unsafe.park(Native Method)
    at java.base@11.0.5/java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source)
    at java.base@11.0.5/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(Unknown Source)
    at java.base@11.0.5/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(Unknown Source)
    at java.base@11.0.5/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(Unknown Source)
    at java.base@11.0.5/java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
    at java.base@11.0.5/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.base@11.0.5/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.base@11.0.5/java.lang.Thread.run(Unknown Source)

logback-11 id=296074 state=WAITING
    - waiting on <0x579f0c03> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
    - locked <0x579f0c03> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
    at java.base@11.0.5/jdk.internal.misc.Unsafe.park(Native Method)
    at java.base@11.0.5/java.util.concurrent.locks.LockSupport.park(Unknown Source)
    at java.base@11.0.5/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source)
    at java.base@11.0.5/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(Unknown Source)
    at java.base@11.0.5/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(Unknown Source)
    at java.base@11.0.5/java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
    at java.base@11.0.5/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.base@11.0.5/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.base@11.0.5/java.lang.Thread.run(Unknown Source)

logback-10 id=296073 state=WAITING
    - waiting on <0x579f0c03> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
    - locked <0x579f0c03> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
    at java.base@11.0.5/jdk.internal.misc.Unsafe.park(Native Method)
    at java.base@11.0.5/java.util.concurrent.locks.LockSupport.park(Unknown Source)
    at java.base@11.0.5/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source)
    at java.base@11.0.5/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(Unknown Source)
    at java.base@11.0.5/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(Unknown Source)
    at java.base@11.0.5/java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
    at java.base@11.0.5/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.base@11.0.5/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.base@11.0.5/java.lang.Thread.run(Unknown Source)

logback-9 id=296071 state=WAITING
    - waiting on <0x579f0c03> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
    - locked <0x579f0c03> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
    at java.base@11.0.5/jdk.internal.misc.Unsafe.park(Native Method)
    at java.base@11.0.5/java.util.concurrent.locks.LockSupport.park(Unknown Source)
    at java.base@11.0.5/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source)
    at java.base@11.0.5/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(Unknown Source)
    at java.base@11.0.5/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(Unknown Source)
    at java.base@11.0.5/java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
    at java.base@11.0.5/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.base@11.0.5/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.base@11.0.5/java.lang.Thread.run(Unknown Source)

logback-8 id=1724 state=WAITING
    - waiting on <0x692c1df1> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
    - locked <0x692c1df1> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
    at java.base@11.0.5/jdk.internal.misc.Unsafe.park(Native Method)
    at java.base@11.0.5/java.util.concurrent.locks.LockSupport.park(Unknown Source)
    at java.base@11.0.5/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source)
    at java.base@11.0.5/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(Unknown Source)
    at java.base@11.0.5/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(Unknown Source)
    at java.base@11.0.5/java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
    at java.base@11.0.5/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.base@11.0.5/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.base@11.0.5/java.lang.Thread.run(Unknown Source)

logback-7 id=1721 state=WAITING
    - waiting on <0x692c1df1> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
    - locked <0x692c1df1> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
    at java.base@11.0.5/jdk.internal.misc.Unsafe.park(Native Method)
    at java.base@11.0.5/java.util.concurrent.locks.LockSupport.park(Unknown Source)
    at java.base@11.0.5/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source)
    at java.base@11.0.5/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(Unknown Source)
    at java.base@11.0.5/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(Unknown Source)
    at java.base@11.0.5/java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
    at java.base@11.0.5/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.base@11.0.5/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.base@11.0.5/java.lang.Thread.run(Unknown Source)

logback-6 id=1719 state=WAITING
    - waiting on <0x692c1df1> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
    - locked <0x692c1df1> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
    at java.base@11.0.5/jdk.internal.misc.Unsafe.park(Native Method)
    at java.base@11.0.5/java.util.concurrent.locks.LockSupport.park(Unknown Source)
    at java.base@11.0.5/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source)
    at java.base@11.0.5/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(Unknown Source)
    at java.base@11.0.5/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(Unknown Source)
    at java.base@11.0.5/java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
    at java.base@11.0.5/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.base@11.0.5/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.base@11.0.5/java.lang.Thread.run(Unknown Source)

logback-5 id=1717 state=TIMED_WAITING
    - waiting on <0x692c1df1> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
    - locked <0x692c1df1> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
    at java.base@11.0.5/jdk.internal.misc.Unsafe.park(Native Method)
    at java.base@11.0.5/java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source)
    at java.base@11.0.5/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(Unknown Source)
    at java.base@11.0.5/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(Unknown Source)
    at java.base@11.0.5/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(Unknown Source)
    at java.base@11.0.5/java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
    at java.base@11.0.5/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.base@11.0.5/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.base@11.0.5/java.lang.Thread.run(Unknown Source)

logback-4 id=1716 state=WAITING
    - waiting on <0x692c1df1> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
    - locked <0x692c1df1> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
    at java.base@11.0.5/jdk.internal.misc.Unsafe.park(Native Method)
    at java.base@11.0.5/java.util.concurrent.locks.LockSupport.park(Unknown Source)
    at java.base@11.0.5/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source)
    at java.base@11.0.5/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(Unknown Source)
    at java.base@11.0.5/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(Unknown Source)
    at java.base@11.0.5/java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
    at java.base@11.0.5/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.base@11.0.5/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.base@11.0.5/java.lang.Thread.run(Unknown Source)

logback-3 id=1715 state=WAITING
    - waiting on <0x692c1df1> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
    - locked <0x692c1df1> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
    at java.base@11.0.5/jdk.internal.misc.Unsafe.park(Native Method)
    at java.base@11.0.5/java.util.concurrent.locks.LockSupport.park(Unknown Source)
    at java.base@11.0.5/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source)
    at java.base@11.0.5/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(Unknown Source)
    at java.base@11.0.5/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(Unknown Source)
    at java.base@11.0.5/java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
    at java.base@11.0.5/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.base@11.0.5/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.base@11.0.5/java.lang.Thread.run(Unknown Source)

logback-2 id=1714 state=WAITING
    - waiting on <0x692c1df1> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
    - locked <0x692c1df1> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
    at java.base@11.0.5/jdk.internal.misc.Unsafe.park(Native Method)
    at java.base@11.0.5/java.util.concurrent.locks.LockSupport.park(Unknown Source)
    at java.base@11.0.5/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source)
    at java.base@11.0.5/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(Unknown Source)
    at java.base@11.0.5/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(Unknown Source)
    at java.base@11.0.5/java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
    at java.base@11.0.5/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.base@11.0.5/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.base@11.0.5/java.lang.Thread.run(Unknown Source)

logback-1 id=1713 state=WAITING
    - waiting on <0x692c1df1> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
    - locked <0x692c1df1> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
    at java.base@11.0.5/jdk.internal.misc.Unsafe.park(Native Method)
    at java.base@11.0.5/java.util.concurrent.locks.LockSupport.park(Unknown Source)
    at java.base@11.0.5/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source)
    at java.base@11.0.5/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(Unknown Source)
    at java.base@11.0.5/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(Unknown Source)
    at java.base@11.0.5/java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
    at java.base@11.0.5/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.base@11.0.5/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.base@11.0.5/java.lang.Thread.run(Unknown Source)
```
Looking at `ch.qos.logback.core.util.ExecutorServiceUtil` it is possible to conclude that they all use the same logback static ThreadFactory (as they share counter), and they dong get beyond `ch.qos.logback.core.CoreConstants#SCHEDULED_EXECUTOR_POOL_SIZE` in each pool

Due to `synchronized` block it is possible only there are many `LoggerContext` instances. It is created in logback-classic `StaticLoggerBinder` only and in turn only in LoggerFactory of slf4japi.
So problem is in classloading (OSGi) and possibly because apps have own slf4j/logback included.

**Comment by rymsha** [comment]
It is likely due to how Log Browser Application is implemented.

**Comment by rymsha** [comment]
With no Log Browser app in use this issue is not reproducible
