### ISSUE TITLE
XP crashes on second boot with CLI

### ISSUE THREAD

**Issue by sigdestad** [enonic/xp#6931]
Used enonic project deploy, second time XP failed seriously spamming the log with this info:

], s[INITIALIZING], a[id=wLz24qOaSTGXFKmQ_PnNKQ], unassigned_info[[reason=ALLOCATION_FAILED], at[2019-02-12T10:57:39.314Z], details[failed recovery, failure IndexShardRecoveryException[failed to recovery from gateway]; nested: EngineCreationFailureException[failed to create engine]; nested: EOFException; ]]], indexUUID [qVumxMSoQN6mpr-Jt60EoQ], message [failed recovery], failure [IndexShardRecoveryException[failed to recovery from gateway]; nested: EngineCreationFailureException[failed to create engine]; nested: EOFException; ]
org.elasticsearch.index.shard.IndexShardRecoveryException: failed to recovery from gateway
	at org.elasticsearch.index.shard.StoreRecoveryService.recoverFromStore(StoreRecoveryService.java:250)
	at org.elasticsearch.index.shard.StoreRecoveryService.access$100(StoreRecoveryService.java:56)
	at org.elasticsearch.index.shard.StoreRecoveryService$1.run(StoreRecoveryService.java:129)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.elasticsearch.index.engine.EngineCreationFailureException: failed to create engine
	at org.elasticsearch.index.engine.InternalEngine.<init>(InternalEngine.java:152)
	at org.elasticsearch.index.engine.InternalEngineFactory.newReadWriteEngine(InternalEngineFactory.java:25)
	at org.elasticsearch.index.shard.IndexShard.newEngine(IndexShard.java:1513)
	at org.elasticsearch.index.shard.IndexShard.createNewEngine(IndexShard.java:1497)
	at org.elasticsearch.index.shard.IndexShard.internalPerformTranslogRecovery(IndexShard.java:970)
	at org.elasticsearch.index.shard.IndexShard.performTranslogRecovery(IndexShard.java:942)
	at org.elasticsearch.index.shard.StoreRecoveryService.recoverFromStore(StoreRecoveryService.java:241)
	... 5 common frames omitted
Caused by: java.io.EOFException: null
	at org.apache.lucene.store.InputStreamDataInput.readByte(InputStreamDataInput.java:37)
	at org.apache.lucene.store.DataInput.readInt(DataInput.java:101)
	at org.apache.lucene.store.DataInput.readLong(DataInput.java:157)
	at org.elasticsearch.index.translog.Checkpoint.<init>(Checkpoint.java:54)
	at org.elasticsearch.index.translog.Checkpoint.read(Checkpoint.java:83)
	at org.elasticsearch.index.translog.Translog.recoverFromFiles(Translog.java:337)
	at org.elasticsearch.index.translog.Translog.<init>(Translog.java:179)
	at org.elasticsearch.index.engine.InternalEngine.openTranslog(InternalEngine.java:205)
	at org.elasticsearch.index.engine.InternalEngine.<init>(InternalEngine.java:148)
	... 11 common frames omitted
2019-02-12 11:57:39,326 WARN  org.elasticsearch.indices.cluster - [24406af8-6715-4ce4-acd4-89c5873c5069] [[storage-com.enonic.cms.default][0]] marking and sending shard failed due to [failed recovery]
org.elasticsearch.index.shard.IndexShardRecoveryException: failed to recovery from gateway
	at org.elasticsearch.index.shard.StoreRecoveryService.recoverFromStore(StoreRecoveryService.java:250)
	at org.elasticsearch.index.shard.StoreRecoveryService.access$100(StoreRecoveryService.java:56)
	at org.elasticsearch.index.shard.StoreRecoveryService$1.run(StoreRecoveryService.java:129)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.elasticsearch.index.engine.EngineCreationFailureException: failed to create engine
	at org.elasticsearch.index.engine.InternalEngine.<init>(InternalEngine.java:152)
	at org.elasticsearch.index.engine.InternalEngineFactory.newReadWriteEngine(InternalEngineFactory.java:25)
	at org.elasticsearch.index.shard.IndexShard.newEngine(IndexShard.java:1513)
	at org.elasticsearch.index.shard.IndexShard.createNewEngine(IndexShard.java:1497)
	at org.elasticsearch.index.shard.IndexShard.internalPerformTranslogRecovery(IndexShard.java:970)
	at org.elasticsearch.index.shard.IndexShard.performTranslogRecovery(IndexShard.java:942)
	at org.elasticsearch.index.shard.StoreRecoveryService.recoverFromStore(StoreRecoveryService.java:241)
	... 5 common frames omitted
Caused by: java.io.EOFException: null
	at org.apache.lucene.store.InputStreamDataInput.readByte(InputStreamDataInput.java:37)
	at org.apache.lucene.store.DataInput.readInt(DataInput.java:101)
	at org.apache.lucene.store.DataInput.readLong(DataInput.java:157)
	at org.elasticsearch.index.translog.Checkpoint.<init>(Checkpoint.java:54)
	at org.elasticsearch.index.translog.Checkpoint.read(Checkpoint.java:83)
	at org.elasticsearch.index.translog.Translog.recoverFromFiles(Translog.java:337)
	at org.elasticsearch.index.translog.Translog.<init>(Translog.java:179)
	at org.elasticsearch.index.engine.InternalEngine.openTranslog(InternalEngine.java:205)
	at org.elasticsearch.index.engine.InternalEngine.<init>(InternalEngine.java:148)
	... 11 common frames omitted
2019-02-12 11:57:39,326 WARN  o.elasticsearch.cluster.action.shard - [24406af8-6715-4ce4-acd4-89c5873c5069] [storage-com.enonic.cms.default][0] received shard failed for target shard [[storage-com.enonic.cms.default][0], node[5Iku8F00RVihdOQEKxp3Lw], [P], v[1630], s[INITIALIZING], a[id=FwXavpiVSGapq9JJ_H6K1A], unassigned_info[[reason=ALLOCATION_FAILED], at[2019-02-12T10:57:39.320Z], details[failed recovery, failure IndexShardRecoveryException[failed to recovery from gateway]; nested: EngineCreationFailureException[failed to create engine]; nested: EOFException; ]]], indexUUID [qVumxMSoQN6mpr-Jt60EoQ], message [failed recovery], failure [IndexShardRecoveryException[failed to recovery from gateway]; nested: EngineCreationFailureException[failed to create engine]; nested: EOFException; ]
org.elasticsearch.index.shard.IndexShardRecoveryException: failed to recovery from gateway
	at org.elasticsearch.index.shard.StoreRecoveryService.recoverFromStore(StoreRecoveryService.java:250)
	at org.elasticsearch.index.shard.StoreRecoveryService.access$100(StoreRecoveryService.java:56)
	at org.elasticsearch.index.shard.StoreRecoveryService$1.run(StoreRecoveryService.java:129)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.elasticsearch.index.engine.EngineCreationFailureException: failed to create engine
	at org.elasticsearch.index.engine.InternalEngine.<init>(InternalEngine.java:152)
	at org.elasticsearch.index.engine.InternalEngineFactory.newReadWriteEngine(InternalEngineFactory.java:25)
	at org.elasticsearch.index.shard.IndexShard.newEngine(IndexShard.java:1513)
	at org.elasticsearch.index.shard.IndexShard.createNewEngine(IndexShard.java:1497)
	at org.elasticsearch.index.shard.IndexShard.internalPerformTranslogRecovery(IndexShard.java:970)
	at org.elasticsearch.index.shard.IndexShard.performTranslogRecovery(IndexShard.java:942)
	at org.elasticsearch.index.shard.StoreRecoveryService.recoverFromStore(StoreRecoveryService.java:241)
	... 5 common frames omitted
Caused by: java.io.EOFException: null
	at org.apache.lucene.store.InputStreamDataInput.readByte(InputStreamDataInput.java:37)
	at org.apache.lucene.store.DataInput.readInt(DataInput.java:101)
	at org.apache.lucene.store.DataInput.readLong(DataInput.java:157)
	at org.elasticsearch.index.translog.Checkpoint.<init>(Checkpoint.java:54)
	at org.elasticsearch.index.translog.Checkpoint.read(Checkpoint.java:83)
	at org.elasticsearch.index.translog.Translog.recoverFromFiles(Translog.java:337)
	at org.elasticsearch.index.translog.Translog.<init>(Translog.java:179)
	at org.elasticsearch.index.engine.InternalEngine.openTranslog(InternalEngine.java:205)
	at org.elasticsearch.index.engine.InternalEngine.<init>(InternalEngine.java:148)
	... 11 common frames omitted
2019-02-12 11:57:39,330 INFO  c.e.x.l.i.framework.FrameworkService - Server has been stopped

**Comment by alansemenov** [comment]
@sigdestad is this still an issue?

**Comment by sigdestad** [comment]
Not that I know
