### ISSUE TITLE
Exception in version history panel

### ISSUE THREAD

**Issue by vbradnitski** [enonic/xp#7063]
@sgauruseu commented on [Thu Apr 04 2019](https://github.com/enonic/app-contentstudio/issues/393)

1. Install SuperHero
2. Open Filter Panel and check `Post` (Comment, Landing Page)
3. Select any post-content and try to open Versions Widget

![image](https://user-images.githubusercontent.com/3728712/55553543-246cf580-56e9-11e9-83d5-4153545f60b0.png)

**BUG**:
**NullPointerException in server.log and 
500 error in console**

java.lang.NullPointerException: null
        at com.enonic.xp.core.impl.content.ContentVersionFactory.doCreateContentVersion(ContentVersionFactory.java:53)
        at com.enonic.xp.core.impl.content.ContentVersionFactory.create(ContentVersionFactory.java:43)
        at com.enonic.xp.core.impl.content.ContentVersionFactory.create(ContentVersionFactory.java:33)
        at com.enonic.xp.core.impl.content.FindContentVersionsCommand.doGetContentVersions(FindContentVersionsCommand.java:60)
        at com.enonic.xp.core.impl.content.FindContentVersionsCommand.execute(FindContentVersionsCommand.java:37)
        at com.enonic.xp.core.impl.content.ContentServiceImpl.getVersions(ContentServiceImpl.java:897)
        at com.enonic.xp.admin.impl.rest.resource.content.ContentResource.getContentVersionsForView(ContentResource.java:1234)

**Comment by GlennRicaud** [comment]
That should never happened.
Somebody made an update and broke 23 nodes a year ago: https://github.com/enonic/app-superhero-blog/commit/0c98e4b53c70fce86150a43d289c2862015992c9
Closing this issue. Please fix the 23 nodes in app-superhero-blog
