### ISSUE TITLE
Make schedule optional on PublishRequestIssue

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp#7271]
Steps to reproduce: 
1. Open new folder wizard , type a name.
2.  Select `Publish...` menu item.

![image](https://user-images.githubusercontent.com/3728712/62209581-a7a20d80-b3a2-11e9-8edb-f59307170a59.png)

Caused by: java.lang.NullPointerException: text
	at java.base/java.util.Objects.requireNonNull(Objects.java:246)
	at java.base/java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1945)
	at java.base/java.time.Instant.parse(Instant.java:395)
	at com.enonic.xp.admin.impl.rest.resource.content.json.PublishScheduleJson.<init>(PublishScheduleJson.java:18)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.fasterxml.jackson.databind.introspect.AnnotatedConstructor.call(AnnotatedConstructor.java:124)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromObjectWith(StdValueInstantiator.java:283)
	... 95 common frames omitted

**Comment by GlennRicaud** [comment]
@pmi: I do not thing this is the problem. Please fix in ContentStudio

**Comment by alansemenov** [comment]
@pmi `publishFrom` can never be null. if it's not set then we set it to `Now()` (that's how it used to be before as well)

**Comment by pmi** [comment]
@alansemenov @GlennRicaud ok I will add required and set publishFrom to Now() if no schedule is set.

But there are other things here: I can send entire PublishSchedule == null to publish content endpoint, which will publish it, but will give errors later when listing it. That is not the case with create issue endpoint where null PublishSchedule is not allowed.

**Comment by GlennRicaud** [comment]
"but will give errors later when listing it" when listing what?

/admin/rest/content/publish: schedule is optional. But if it is specified it should have a "from"

/admin/rest/issue/create:
If issue of type "PUBLISH_REQUEST" -> It needs a schedule. I have not been given much info about what is mandatory or not here. I think we should have "from" mandatory.
Else -> schedule is ignored

**Comment by GlennRicaud** [comment]
So from what I understand here, the things to do in XP:
- Revert this modification
- Add @JsonProperty(value = "from", required = true) in PublishScheduleJson.java
- Make schedule optional for PUBLISH_REQUEST issues.
  - Adapt 
-  Make from mandatory on PublishRequestIssueSchedule

**Comment by alansemenov** [comment]
I suggest we follow the standard practice of pull requests for changes in this epic (only in this repo, not necessary for `lib-admin-ui` and `app-contentstudio`)

**Comment by pmi** [comment]
Okay,

Here is the PR to XP https://github.com/enonic/xp/pull/7278

And PR to CS since CS changes are dependent on XP ones https://github.com/enonic/app-contentstudio/pull/705
