### ISSUE TITLE
System dump archive NullPointerException when loading system dump from archive

### ISSUE THREAD

**Issue by gbbirkisson** [enonic/xp#8106]
Trying to load a system dump with approximately 10000 content from 7.2.4 to 7.3.0 that was zipped by data toolbox:

```
java.lang.NullPointerException: null
	at com.enonic.xp.repo.impl.dump.reader.AbstractDumpReader.readDumpMetaData(AbstractDumpReader.java:218)
	at com.enonic.xp.repo.impl.dump.reader.AbstractDumpReader.getDumpMeta(AbstractDumpReader.java:197)
	at com.enonic.xp.repo.impl.dump.DumpServiceImpl.load(DumpServiceImpl.java:284)
	at com.enonic.xp.impl.server.rest.task.LoadRunnableTask.doLoadFromSystemDump(LoadRunnableTask.java:151)
	at com.enonic.xp.impl.server.rest.task.LoadRunnableTask.run(LoadRunnableTask.java:79)
	at com.enonic.xp.impl.task.TaskWrapper.lambda$callTaskWithContext$0(TaskWrapper.java:90)
	at com.enonic.xp.context.ContextImpl.callWith(ContextImpl.java:102)
	at com.enonic.xp.impl.task.TaskWrapper.callTaskWithContext(TaskWrapper.java:89)
	at com.enonic.xp.impl.task.TaskWrapper.doRun(TaskWrapper.java:75)
	at com.enonic.xp.impl.task.TaskWrapper.run(TaskWrapper.java:59)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

Zip available at: https://enonic.slack.com/archives/DPQ8SS89Z/p1590136424001200

**Comment by rymsha** [comment]
First of all - It is an "expected behavior" because zip file name should be called equally with its folder inside.
But it should not throw NPE - this is for sure. Better to be some sort of "Invalid archive dump file" error message.

Secondly - maybe "load" needs to be smarter and seek for `dump.json` file (metadata) in folders within the archive (`/dump.json`, `/a.../dump.json`, `/b.../dump.json`, but not `/a/b/dump.json`) so renaming zip file won't be so destructive. 

What do you think @gbbirkisson ?

**Comment by gbbirkisson** [comment]
Yeah now I remember you told me this :smile: 

This is definitely going to come up when people start using this. I think looking for the `dump.json` is a great idea to make it more robust.
