### ISSUE TITLE
Endless loop when calling application market

### ISSUE THREAD

**Issue by rymsha** [enonic/xp#8159]
How to reproduce:

Running Any OS, any browser
Start clean sandbox with ~~7.3.0~~ 7.2.4 also affected
"login" to admin
Complete wizard by installing the tree apps
Wait ~8 minutes minutes

Result:
 100% CPU

**Comment by rymsha** [comment]
```
"HttpClient-1-Worker-5" id=268 state=RUNNABLE
    at java.base@11.0.7/java.util.AbstractList.listIterator(AbstractList.java:311)
    at java.base@11.0.7/java.util.AbstractSequentialList.iterator(AbstractSequentialList.java:238)
    at java.base@11.0.7/java.util.Collections$SynchronizedCollection.iterator(Collections.java:2036)
    at platform/java.net.http@11.0.7/jdk.internal.net.http.common.SSLFlowDelegate.cleanList(SSLFlowDelegate.java:942)
    at platform/java.net.http@11.0.7/jdk.internal.net.http.common.SSLFlowDelegate$Writer.processData(SSLFlowDelegate.java:768)
    at platform/java.net.http@11.0.7/jdk.internal.net.http.common.SSLFlowDelegate$Writer$WriterDownstreamPusher.run(SSLFlowDelegate.java:646)
    at platform/java.net.http@11.0.7/jdk.internal.net.http.common.SequentialScheduler$CompleteRestartableTask.run(SequentialScheduler.java:147)
    at platform/java.net.http@11.0.7/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:198)
    at platform/java.net.http@11.0.7/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:271)
    at platform/java.net.http@11.0.7/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:224)
    at platform/java.net.http@11.0.7/jdk.internal.net.http.common.SSLFlowDelegate$Writer.triggerWrite(SSLFlowDelegate.java:723)
    at platform/java.net.http@11.0.7/jdk.internal.net.http.common.SSLFlowDelegate.doHandshake(SSLFlowDelegate.java:1038)
    at platform/java.net.http@11.0.7/jdk.internal.net.http.common.SSLFlowDelegate.doClosure(SSLFlowDelegate.java:1124)
    at platform/java.net.http@11.0.7/jdk.internal.net.http.common.SSLFlowDelegate$Reader.unwrapBuffer(SSLFlowDelegate.java:501)
    at platform/java.net.http@11.0.7/jdk.internal.net.http.common.SSLFlowDelegate$Reader.processData(SSLFlowDelegate.java:392)
      - locked java.lang.Object@6eeba5bc
    at platform/java.net.http@11.0.7/jdk.internal.net.http.common.SSLFlowDelegate$Reader$ReaderDownstreamPusher.run(SSLFlowDelegate.java:264)
    at platform/java.net.http@11.0.7/jdk.internal.net.http.common.SequentialScheduler$SynchronizedRestartableTask.run(SequentialScheduler.java:175)
      - locked java.lang.Object@13de8697
    at platform/java.net.http@11.0.7/jdk.internal.net.http.common.SequentialScheduler$CompleteRestartableTask.run(SequentialScheduler.java:147)
    at platform/java.net.http@11.0.7/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:198)
    at java.base@11.0.7/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base@11.0.7/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base@11.0.7/java.lang.Thread.run(Thread.java:834)
    Locked synchronizers: count = 1
      - java.util.concurrent.ThreadPoolExecutor$Worker@27341f0b
```

**Comment by rymsha** [comment]
Related to but not caused by golang/go#35722 . It gives an idea that recently Go "improved" their  TLS1.3 support, and these improvements had started to spread all over the websites, including Cloudflare, I guess. 
Java fixes all related issues quickly but mostly in newest versions (JDK 12-14) slowly backporting them to JDK 11 LTS.
We are affected by an issue with a fix https://bugs.openjdk.java.net/browse/JDK-8241054 not yet released (supposed to be fixed in 11.0.8 - mid July 2020)

In general TLS1.3 is quite new and not yet well understood technology. Different implementations (OpenSSL, Java, Go, ...) still may not work well together. 

Browser Support of TLS1.3 is still sparse. We may want to disable outgoing TLS1.3 support as TLS1.2 will be still supported for quite a while.

**Comment by rymsha** [comment]
Some say that disabling TLS1.3 won't help.
https://stackoverflow.com/questions/55298459/java-11-httpclient-leads-to-endless-ssl-loop-even-with-disabled-tlsv-1-3

Need to verify

**Comment by rymsha** [comment]
This is on hold. We hope that JDK 11.0.8 resolves it.

**Comment by rymsha** [comment]
7.3.1 bundles JDK 11.0.8

**Comment by r9liucc** [comment]
@rymsha 
Hi, Does JDK 11.0.8 fix the issue? 
Our team met the same issue too.

**Comment by rymsha** [comment]
We removed use of httpclient entirely. We don't know if JDK fix solves the problem

**Comment by sigdestad** [comment]
I'm quite sure we did a test that shows 11.0.8 fixed the problem...
