### ISSUE TITLE
Application crashes in 7.3 not in 7.2.4

### ISSUE THREAD

**Issue by poi33** [enonic/xp#8225]
While debugging the formbuilder-app noticed that its crashes on 7.3 while the same code does not on 7.2.

The crash is caused by content api: 
```
contentLib.create({
        name: '_attachments',
        parentPath: "/",
        displayName: '_attachments',
        draft: true,
        contentType: 'base:folder',
        data: {},
        branch: 'draft'
      });
```

Reproduce, install the formbuilder app on a clean 7.2 sandbox
Then create a form with a file input. 
Try to submit the form -> no crash.

Upgrade the sand to 7.3
Form submit -> crash

Stack trace:

<details><summary>Click to see stack trace</summary><p><code>
2020-07-13 14:54:46,638 ERROR c.e.x.p.i.e.ExceptionRendererImpl - BaseSchemaName can't be null
com.enonic.xp.web.WebException: BaseSchemaName can't be null
        at com.enonic.xp.web.impl.exception.ExceptionMapperImpl.map(ExceptionMapperImpl.java:33)
        at com.enonic.xp.portal.handler.BasePortalHandler.handleError(BasePortalHandler.java:60)
        at com.enonic.xp.portal.handler.BasePortalHandler.doHandle(BasePortalHandler.java:52)
        at com.enonic.xp.web.handler.BaseWebHandler.handle(BaseWebHandler.java:66)
        at com.enonic.xp.web.impl.handler.WebHandlerChainImpl.handle(WebHandlerChainImpl.java:30)
        at com.enonic.xp.web.handler.BaseWebHandler.handle(BaseWebHandler.java:75)
        at com.enonic.xp.web.impl.handler.WebHandlerChainImpl.handle(WebHandlerChainImpl.java:30)
        at com.enonic.xp.web.handler.BaseWebHandler.handle(BaseWebHandler.java:75)
        at com.enonic.xp.web.impl.handler.WebHandlerChainImpl.handle(WebHandlerChainImpl.java:30)
        at com.enonic.xp.web.impl.trace.TraceWebFilter.doHandle(TraceWebFilter.java:38)
        at com.enonic.xp.web.handler.BaseWebHandler.handle(BaseWebHandler.java:66)
        at com.enonic.xp.web.impl.handler.WebHandlerChainImpl.handle(WebHandlerChainImpl.java:30)
        at com.enonic.xp.web.impl.handler.WebDispatcherImpl.dispatch(WebDispatcherImpl.java:44)
        at com.enonic.xp.web.impl.handler.WebDispatcherServlet.doHandle(WebDispatcherServlet.java:142)
        at com.enonic.xp.web.impl.handler.WebDispatcherServlet.service(WebDispatcherServlet.java:70)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at com.enonic.xp.web.impl.dispatch.mapping.ServletDefinitionImpl.service(ServletDefinitionImpl.java:40)
        at com.enonic.xp.web.impl.dispatch.pipeline.ServletPipelineImpl.service(ServletPipelineImpl.java:40)
        at com.enonic.xp.web.impl.dispatch.pipeline.FilterChainImpl.doFilter(FilterChainImpl.java:45)
        at com.enonic.xp.web.impl.dispatch.pipeline.FilterChainImpl.doFilter(FilterChainImpl.java:36)
        at com.enonic.xp.portal.impl.idprovider.IdProviderFilter.doHandle(IdProviderFilter.java:45)
        at com.enonic.xp.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:31)
        at com.enonic.xp.web.filter.BaseWebFilter.doFilter(BaseWebFilter.java:33)
        at com.enonic.xp.web.impl.dispatch.mapping.FilterDefinitionImpl.doFilter(FilterDefinitionImpl.java:41)
        at com.enonic.xp.web.impl.dispatch.pipeline.FilterChainImpl.doFilter(FilterChainImpl.java:50)
        at com.enonic.xp.web.impl.dispatch.pipeline.FilterChainImpl.doFilter(FilterChainImpl.java:36)
        at com.enonic.xp.web.impl.auth.BasicAuthFilter.doHandle(BasicAuthFilter.java:34)
        at com.enonic.xp.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:31)
        at com.enonic.xp.web.filter.BaseWebFilter.doFilter(BaseWebFilter.java:33)
        at com.enonic.xp.web.impl.dispatch.mapping.FilterDefinitionImpl.doFilter(FilterDefinitionImpl.java:41)
        at com.enonic.xp.web.impl.dispatch.pipeline.FilterChainImpl.doFilter(FilterChainImpl.java:50)
        at com.enonic.xp.web.impl.dispatch.pipeline.FilterChainImpl.doFilter(FilterChainImpl.java:36)
        at com.enonic.xp.web.impl.context.ContextFilter.lambda$doHandle$0(ContextFilter.java:33)
        at com.enonic.xp.context.ContextImpl.callWith(ContextImpl.java:102)
        at com.enonic.xp.web.impl.context.ContextFilter.doHandle(ContextFilter.java:32)
        at com.enonic.xp.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:31)
        at com.enonic.xp.web.filter.BaseWebFilter.doFilter(BaseWebFilter.java:33)
        at com.enonic.xp.web.impl.dispatch.mapping.FilterDefinitionImpl.doFilter(FilterDefinitionImpl.java:41)
        at com.enonic.xp.web.impl.dispatch.pipeline.FilterChainImpl.doFilter(FilterChainImpl.java:50)
        at com.enonic.xp.web.impl.dispatch.pipeline.FilterChainImpl.doFilter(FilterChainImpl.java:36)
        at com.enonic.xp.web.vhost.impl.VirtualHostFilter.doHandle(VirtualHostFilter.java:60)
        at com.enonic.xp.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:31)
        at com.enonic.xp.web.filter.BaseWebFilter.doFilter(BaseWebFilter.java:33)
        at com.enonic.xp.web.impl.dispatch.mapping.FilterDefinitionImpl.doFilter(FilterDefinitionImpl.java:41)
        at com.enonic.xp.web.impl.dispatch.pipeline.FilterChainImpl.doFilter(FilterChainImpl.java:50)
        at com.enonic.xp.web.impl.dispatch.pipeline.FilterChainImpl.doFilter(FilterChainImpl.java:36)
        at com.enonic.xp.web.impl.dos.DosFilterWrapper.doFilter(DosFilterWrapper.java:65)
        at com.enonic.xp.web.impl.dispatch.mapping.FilterDefinitionImpl.doFilter(FilterDefinitionImpl.java:41)
        at com.enonic.xp.web.impl.dispatch.pipeline.FilterChainImpl.doFilter(FilterChainImpl.java:50)
        at com.enonic.xp.web.impl.dispatch.pipeline.FilterChainImpl.doFilter(FilterChainImpl.java:36)
        at org.eclipse.jetty.servlets.HeaderFilter.doFilter(HeaderFilter.java:117)
        at com.enonic.xp.web.impl.header.HeaderFilterWrapper.doHandle(HeaderFilterWrapper.java:51)
        at com.enonic.xp.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:31)
        at com.enonic.xp.web.filter.BaseWebFilter.doFilter(BaseWebFilter.java:33)
        at com.enonic.xp.web.impl.dispatch.mapping.FilterDefinitionImpl.doFilter(FilterDefinitionImpl.java:41)
        at com.enonic.xp.web.impl.dispatch.pipeline.FilterChainImpl.doFilter(FilterChainImpl.java:50)
        at com.enonic.xp.web.impl.dispatch.pipeline.FilterChainImpl.doFilter(FilterChainImpl.java:36)
        at com.enonic.xp.web.impl.dispatch.pipeline.FilterPipelineImpl.filter(FilterPipelineImpl.java:39)
        at com.enonic.xp.web.impl.dispatch.DispatchServletImpl.service(DispatchServletImpl.java:52)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:763)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:551)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:717)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1610)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1363)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:489)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1580)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1278)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:221)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at com.codahale.metrics.jetty9.InstrumentedHandler.handle(InstrumentedHandler.java:249)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at org.eclipse.jetty.server.Server.handle(Server.java:500)
        at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:547)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.enonic.xp.resource.ResourceProblemException: BaseSchemaName can't be null
        at com.enonic.xp.resource.ResourceProblemException$Builder.build(ResourceProblemException.java:131)
        at com.enonic.xp.script.impl.util.ErrorHelper.doHandleException(ErrorHelper.java:54)
        at com.enonic.xp.script.impl.util.ErrorHelper.handleError(ErrorHelper.java:27)
        at com.enonic.xp.script.impl.value.FunctionScriptValue.call(FunctionScriptValue.java:41)
        at com.enonic.xp.script.impl.executor.ScriptExportsImpl.executeMethod(ScriptExportsImpl.java:59)
        at com.enonic.xp.portal.impl.controller.ControllerScriptImpl.doExecute(ControllerScriptImpl.java:71)
        at com.enonic.xp.portal.impl.controller.ControllerScriptImpl.lambda$execute$0(ControllerScriptImpl.java:36)
        at com.enonic.xp.trace.Tracer.traceEx(Tracer.java:72)
        at com.enonic.xp.trace.Tracer.trace(Tracer.java:51)
        at com.enonic.xp.trace.Tracer.trace(Tracer.java:98)
        at com.enonic.xp.portal.impl.controller.ControllerScriptImpl.execute(ControllerScriptImpl.java:36)
        at com.enonic.xp.portal.impl.rendering.DescriptorBasedComponentRenderer.doRender(DescriptorBasedComponentRenderer.java:75)
        at com.enonic.xp.portal.impl.rendering.DescriptorBasedComponentRenderer.render(DescriptorBasedComponentRenderer.java:43)
        at com.enonic.xp.portal.impl.rendering.DescriptorBasedComponentRenderer.render(DescriptorBasedComponentRenderer.java:22)
        at com.enonic.xp.portal.impl.rendering.RendererDelegateImpl.lambda$render$1(RendererDelegateImpl.java:40)
        at java.base/java.util.Optional.map(Optional.java:265)
        at com.enonic.xp.portal.impl.rendering.RendererDelegateImpl.render(RendererDelegateImpl.java:40)
        at com.enonic.xp.portal.impl.handler.render.ComponentHandlerWorker.execute(ComponentHandlerWorker.java:123)
        at com.enonic.xp.portal.impl.handler.render.ComponentHandler.doHandle(ComponentHandler.java:66)
        at com.enonic.xp.portal.impl.handler.render.ComponentHandler.doHandle(ComponentHandler.java:23)
        at com.enonic.xp.web.handler.BaseWebHandler.handle(BaseWebHandler.java:66)
        at com.enonic.xp.web.impl.handler.WebHandlerChainImpl.handle(WebHandlerChainImpl.java:30)
        at com.enonic.xp.web.handler.BaseWebHandler.handle(BaseWebHandler.java:75)
        at com.enonic.xp.web.impl.handler.WebHandlerChainImpl.handle(WebHandlerChainImpl.java:30)
        at com.enonic.xp.web.handler.BaseWebHandler.handle(BaseWebHandler.java:75)
        at com.enonic.xp.web.impl.handler.WebHandlerChainImpl.handle(WebHandlerChainImpl.java:30)
        at com.enonic.xp.web.handler.BaseWebHandler.handle(BaseWebHandler.java:75)
        at com.enonic.xp.web.impl.handler.WebHandlerChainImpl.handle(WebHandlerChainImpl.java:30)
        at com.enonic.xp.web.handler.BaseWebHandler.handle(BaseWebHandler.java:75)
        at com.enonic.xp.web.impl.handler.WebHandlerChainImpl.handle(WebHandlerChainImpl.java:30)
        at com.enonic.xp.web.handler.BaseWebHandler.handle(BaseWebHandler.java:75)
        at com.enonic.xp.web.impl.handler.WebHandlerChainImpl.handle(WebHandlerChainImpl.java:30)
        at com.enonic.xp.web.handler.BaseWebHandler.handle(BaseWebHandler.java:75)
        at com.enonic.xp.web.impl.handler.WebHandlerChainImpl.handle(WebHandlerChainImpl.java:30)
        at com.enonic.xp.web.handler.BaseWebHandler.handle(BaseWebHandler.java:75)
        at com.enonic.xp.web.impl.handler.WebHandlerChainImpl.handle(WebHandlerChainImpl.java:30)
        at com.enonic.xp.web.handler.BaseWebHandler.handle(BaseWebHandler.java:75)
        at com.enonic.xp.web.impl.handler.WebHandlerChainImpl.handle(WebHandlerChainImpl.java:30)
        at com.enonic.xp.portal.handler.BasePortalHandler.doHandle(BasePortalHandler.java:46)
        ... 92 common frames omitted
Caused by: java.lang.NullPointerException: BaseSchemaName can't be null
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:895)
        at com.enonic.xp.schema.BaseSchemaName.<init>(BaseSchemaName.java:21)
        at com.enonic.xp.schema.content.ContentTypeName.<init>(ContentTypeName.java:61)
        at com.enonic.xp.schema.content.ContentTypeName.from(ContentTypeName.java:329)
        at com.enonic.xp.core.impl.content.serializer.ContentDataSerializer.fromData(ContentDataSerializer.java:171)
        at com.enonic.xp.core.impl.content.ContentNodeTranslator.doTranslate(ContentNodeTranslator.java:77)
        at com.enonic.xp.core.impl.content.ContentNodeTranslator.fromNode(ContentNodeTranslator.java:49)
        at com.enonic.xp.core.impl.content.GetContentByPathCommand.execute(GetContentByPathCommand.java:35)
        at com.enonic.xp.core.impl.content.AbstractContentCommand.getContent(AbstractContentCommand.java:61)
        at com.enonic.xp.core.impl.content.CreateContentCommand.getDefaultLanguage(CreateContentCommand.java:330)
        at com.enonic.xp.core.impl.content.CreateContentCommand.populateLanguage(CreateContentCommand.java:318)
        at com.enonic.xp.core.impl.content.CreateContentCommand.createContentTranslatorParams(CreateContentCommand.java:268)
        at com.enonic.xp.core.impl.content.CreateContentCommand.doExecute(CreateContentCommand.java:109)
        at com.enonic.xp.core.impl.content.CreateContentCommand.execute(CreateContentCommand.java:96)
        at com.enonic.xp.core.impl.content.CreateMediaCommand.doExecute(CreateMediaCommand.java:118)
        at com.enonic.xp.core.impl.content.CreateMediaCommand.execute(CreateMediaCommand.java:54)
        at com.enonic.xp.core.impl.content.ContentServiceImpl.create(ContentServiceImpl.java:291)
        at com.enonic.xp.lib.content.CreateMediaHandler.doExecute(CreateMediaHandler.java:48)
        at com.enonic.xp.lib.content.BaseContextHandler.execute(BaseContextHandler.java:14)
        at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$562$15434A$content.L:1#createMedia(com.enonic.app.formbuilder:/lib/xp/content.js:401)
        at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$561$8658$form_response.L:1#saveFile#result(com.enonic.app.formbuilder:/lib/form-builder/form-response.js:249)
        at jdk.nashorn.javaadapters.java_util_concurrent_Callable.call(Unknown Source)
        at com.enonic.xp.context.ContextImpl.callWith(ContextImpl.java:102)
        at com.enonic.xp.lib.context.ContextHandlerBean.run(ContextHandlerBean.java:36)
        at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$383$1216AA$context.L:1#run(com.enonic.app.formbuilder:/lib/xp/context.js:56)
        at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$553$1566AA$form_response.L:1#runAsSu(com.enonic.app.formbuilder:/lib/form-builder/form-response.js:42)
        at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$559$8354AAA$form_response.L:1#saveFile(com.enonic.app.formbuilder:/lib/form-builder/form-response.js:246)
</code></p></details>

**Comment by rymsha** [comment]
On XP 7.3.0

I installed
- CS 3.0.0
- Superhero blog 2.1.0
- FormBuilder 2.1.0

Superhero has a form with file input on its front-page. Selected a file, submitted a form -> no crash.

**Comment by sigdestad** [comment]
Whoa, this code does not make any sense? We are not creating "content" with the formbuilder, but using the Node API directly?

**Comment by poi33** [comment]
Where in the code do you see this? I can only find cases where we use content api to create nodes.

**Comment by poi33** [comment]
I aslo can not find any form that is related to the formbuilder on the superhero blog. 
The superhero blog does not use the formbuilder to my knowledge.

**Comment by rymsha** [comment]
Problem is reproduced. This is a regression of "default language" feature.

**Comment by sigdestad** [comment]
So, we are using "content API" outside of a content repo in this case?

**Comment by poi33** [comment]
Yes, this is the case. This is done since the formbuilder app has an option to store from responses both inside cms.default and custom repo. 
Should it use node api when dealing with a custom repo?

**Comment by sigdestad** [comment]
I believe this should have been implemented with node api + create attatchments directly, not via content api
