### ISSUE TITLE
500 error after saving a rotated gif content

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp#8277]
1. Upload the gif file.
2. Open the gif an click on rotate button in toolbar
3. Click on Save button

Bug: 500 error after saving the rotated gif

![image](https://user-images.githubusercontent.com/3728712/90127168-6c843980-dd6d-11ea-9e87-8bf88fa886d1.png)

ERROR c.e.x.j.i.e.JsonExceptionMapper - Index 4096 out of bounds for length 4096
java.lang.ArrayIndexOutOfBoundsException: Index 4096 out of bounds for length 4096
        at java.desktop/com.sun.imageio.plugins.gif.GIFImageReader.read(GIFImageReader.java:992)
        at java.desktop/javax.imageio.ImageIO.read(ImageIO.java:1468)
        at java.desktop/javax.imageio.ImageIO.read(ImageIO.java:1363)
        at com.enonic.xp.core.impl.content.processor.ImageContentProcessor.toBufferedImage(ImageContentProcessor.java:232)
        at com.enonic.xp.core.impl.content.processor.ImageContentProcessor.updateImageMetadata(ImageContentProcessor.java:184)
        at com.enonic.xp.core.impl.content.processor.ImageContentProcessor.lambda$processUpdate$3(ImageContentProcessor.java:160)
        at com.enonic.xp.core.impl.content.UpdateContentCommand.editContent(UpdateContentCommand.java:197)
        at com.enonic.xp.core.impl.content.UpdateContentCommand.updateContentWithProcessedData(UpdateContentCommand.java:172)
        at com.enonic.xp.core.impl.content.UpdateContentCommand.runContentProcessors(UpdateContentCommand.java:159)
        at com.enonic.xp.core.impl.content.UpdateContentCommand.processContent(UpdateContentCommand.java:139)
        at com.enonic.xp.core.impl.content.UpdateContentCommand.doExecute(UpdateContentCommand.java:109)
        at com.enonic.xp.core.impl.content.UpdateContentCommand.execute(UpdateContentCommand.java:84)
        at com.enonic.xp.core.impl.content.ContentServiceImpl.update(ContentServiceImpl.java:314)
        at com.enonic.xp.admin.impl.rest.resource.content.ContentResource.update(ContentResource.java:433)
        at jdk.internal.reflect.GeneratedMethodAccessor235.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:138)
        at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:526)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:415)
        at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$0(ResourceMethodInvoker.java:376)
        at org.jboss.resteasy.core.interception.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:356)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:378)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:347)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:320)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:440)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:229)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:135)
        at org.jboss.resteasy.core.interception.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:356)

**Comment by rymsha** [comment]
repetition of #8004 #7140 

And very likely need to be addressed in CS @alansemenov . See enonic/app-contentstudio#479

Java standard library still can't process newest GIFs https://bugs.openjdk.java.net/browse/JDK-7132728 We have it in a backlog. See #8007

**Comment by alansemenov** [comment]
I don't see how this can be solved in CS, unless we simply forbid rotating GIFs in the UI.

**Comment by sigdestad** [comment]
That May very well be an acceptable solution.
