### ISSUE TITLE
NPE when deploying an application without application.xml

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp#8643]
1. Open  Install  dialog and select the application:
[fourth-application-2.0.0.zip](https://github.com/enonic/xp/files/5892864/fourth-application-2.0.0.zip)

Notification warning appears:

![image](https://user-images.githubusercontent.com/3728712/106256543-766efb80-622c-11eb-91a0-f8d2feb9f0f3.png)

**Bug**- application is not installed and errors in the `server.log`

DeployDirectoryWatcher - Failed to install local application
java.lang.NullPointerException: null
        at com.enonic.xp.server.internal.deploy.DeployDirectoryWatcher.installApplication(DeployDirectoryWatcher.java:179)
        at com.enonic.xp.server.internal.deploy.DeployDirectoryWatcher.onFileCreate(DeployDirectoryWatcher.java:134)
        at org.apache.commons.io.monitor.FileAlterationObserver.doCreate(FileAlterationObserver.java:391)
        at org.apache.commons.io.monitor.FileAlterationObserver.checkAndNotify(FileAlterationObserver.java:331)
        at org.apache.commons.io.monitor.FileAlterationObserver.checkAndNotify(FileAlterationObserver.java:305)
        at org.apache.commons.io.monitor.FileAlterationMonitor.run(FileAlterationMonitor.java:184)
        at java.base/java.lang.Thread.run(Thread.java:834)

**The application will be installed** if you add the `application.xml` file

```
<application>
  <description>Test application</description>
</application>
```

**Comment by rymsha** [comment]
duplicate of #8640

**Comment by sgauruseu** [comment]
fixed in https://github.com/enonic/xp/pull/8641
