### ISSUE TITLE
AuditLog failing for user with non-system id provider

### ISSUE THREAD

**Issue by gbbirkisson** [enonic/xp#8650]
XP version 7.4.1

I can see that the auditlog is sometimes failing:

```
Audit log failed
com.enonic.xp.node.NodeAccessException: Access denied to [/] for [CREATE] by user [user:<NON-SYSTEM-ID-PROVIDER>:<ID>] ''<NAME> <EMAIL>''
	at com.enonic.xp.repo.impl.node.NodePermissionsResolver.doRequireContextUserPermission(NodePermissionsResolver.java:43)
	at com.enonic.xp.repo.impl.node.NodePermissionsResolver.requireContextUserPermission(NodePermissionsResolver.java:18)
	at com.enonic.xp.repo.impl.node.CreateNodeCommand.execute(CreateNodeCommand.java:77)
	at com.enonic.xp.repo.impl.node.NodeServiceImpl.doCreate(NodeServiceImpl.java:461)
	at com.enonic.xp.repo.impl.node.NodeServiceImpl.create(NodeServiceImpl.java:449)
	at com.enonic.xp.core.impl.audit.CreateAuditLogCommand.createNode(CreateAuditLogCommand.java:45)
	at com.enonic.xp.core.impl.audit.CreateAuditLogCommand.lambda$execute$0(CreateAuditLogCommand.java:29)
	at com.enonic.xp.context.ContextImpl.callWith(ContextImpl.java:102)
	at com.enonic.xp.core.impl.audit.CreateAuditLogCommand.execute(CreateAuditLogCommand.java:28)
	at com.enonic.xp.core.impl.audit.AuditLogServiceImpl.log(AuditLogServiceImpl.java:61)
	at com.enonic.xp.core.impl.content.ContentAuditLogSupportImpl.lambda$log$22(ContentAuditLogSupportImpl.java:622)
	at com.enonic.xp.context.ContextImpl.callWith(ContextImpl.java:102)
	at com.enonic.xp.core.impl.content.ContentAuditLogSupportImpl.runAsAuditLog(ContentAuditLogSupportImpl.java:656)
	at com.enonic.xp.core.impl.content.ContentAuditLogSupportImpl.log(ContentAuditLogSupportImpl.java:622)
	at com.enonic.xp.core.impl.content.ContentAuditLogSupportImpl.log(ContentAuditLogSupportImpl.java:603)
	at com.enonic.xp.core.impl.content.ContentAuditLogSupportImpl.log(ContentAuditLogSupportImpl.java:627)
	at com.enonic.xp.core.impl.content.ContentAuditLogSupportImpl.doUpdate(ContentAuditLogSupportImpl.java:187)
	at com.enonic.xp.core.impl.content.ContentAuditLogSupportImpl.lambda$update$4(ContentAuditLogSupportImpl.java:171)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source
```

**Comment by rymsha** [comment]
There is a great chance that issue was fixed in 7.6.0
#8511

**Comment by alansemenov** [comment]
@gbbirkisson can you verify if this works in 7.6?

**Comment by gbbirkisson** [comment]
As soon as this customer upgrades, I will verify.

**Comment by vbradnitski** [comment]
tested and couldn't reproduce.

**Comment by gbbirkisson** [comment]
Since this bug has not shown up on any of our newer instances, I think we can safely close this issue!
