### ISSUE TITLE
Error messages from Scheduler Service during dump import

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp#8880]
During import of a dump from 7.6 into 7.7-RC2 lots of these appeared in the log:
```
2021-06-07 15:32:57,609 WARN  c.e.x.i.s.distributed.RescheduleTask - Problem during task scheduling.
com.enonic.xp.repository.RepositoryNotFoundException: Repository with id [system.scheduler] not found
	at com.enonic.xp.repo.impl.node.NodeServiceImpl.lambda$verifyBranchExists$13(NodeServiceImpl.java:1174)
	at com.enonic.xp.context.ContextImpl.runWith(ContextImpl.java:86)
	at com.enonic.xp.repo.impl.node.NodeHelper.runAsAdmin(NodeHelper.java:15)
	at com.enonic.xp.repo.impl.node.NodeServiceImpl.verifyBranchExists(NodeServiceImpl.java:1168)
	at com.enonic.xp.repo.impl.node.NodeServiceImpl.verifyContext(NodeServiceImpl.java:1150)
	at com.enonic.xp.repo.impl.node.NodeServiceImpl.executeFindByParent(NodeServiceImpl.java:361)
	at com.enonic.xp.repo.impl.node.NodeServiceImpl.findByParent(NodeServiceImpl.java:346)
	at com.enonic.xp.impl.scheduler.ListScheduledJobsCommand.doExecute(ListScheduledJobsCommand.java:33)
	at com.enonic.xp.context.ContextImpl.callWith(ContextImpl.java:102)
	at com.enonic.xp.impl.scheduler.ListScheduledJobsCommand.execute(ListScheduledJobsCommand.java:28)
	at com.enonic.xp.impl.scheduler.SchedulerServiceImpl.list(SchedulerServiceImpl.java:116)
	at com.enonic.xp.context.ContextImpl.callWith(ContextImpl.java:102)
	at com.enonic.xp.impl.scheduler.distributed.RescheduleTask.lambda$doRun$0(RescheduleTask.java:53)
	at com.enonic.xp.core.internal.osgi.OsgiSupport.withServiceOrElseGet(OsgiSupport.java:68)
	at com.enonic.xp.core.internal.osgi.OsgiSupport.withService(OsgiSupport.java:96)
	at com.enonic.xp.impl.scheduler.distributed.RescheduleTask.doRun(RescheduleTask.java:52)
	at com.enonic.xp.impl.scheduler.distributed.RescheduleTask.run(RescheduleTask.java:42)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```
followed by two of these:
```
2021-06-07 15:32:59,609 WARN  c.e.x.i.s.distributed.RescheduleTask - Problem during task scheduling.
java.lang.IllegalStateException: No service found interface com.enonic.xp.scheduler.SchedulerService
	at com.enonic.xp.core.internal.osgi.OsgiSupport.lambda$withService$3(OsgiSupport.java:97)
	at com.enonic.xp.core.internal.osgi.OsgiSupport.withServiceOrElseGet(OsgiSupport.java:59)
	at com.enonic.xp.core.internal.osgi.OsgiSupport.withService(OsgiSupport.java:96)
	at com.enonic.xp.impl.scheduler.distributed.RescheduleTask.doRun(RescheduleTask.java:52)
	at com.enonic.xp.impl.scheduler.distributed.RescheduleTask.run(RescheduleTask.java:42)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by rymsha** [comment]
This is because dump-restore varnishes system.scheduler repository. Should be fixed the same way we fixed `system.auditlog`

**Comment by rymsha** [comment]
second stacktrace is already reported #8839 . Not a big deal because when restore happens, scheduler can't work anyway.

**Comment by alansemenov** [comment]
> Not a big deal because when restore happens, scheduler can't work anyway.

If we can avoid this message, let's do that. "`java.lang.IllegalStateException`" in the logs is very likely to raise the questions.

**Comment by rymsha** [comment]
> If we can avoid this message, let's do that

We can't right now. Target is 7.7.1
