### ISSUE TITLE
Creation info is removed after job update

### ISSUE THREAD

**Issue by vbradnitski** [enonic/xp#9049]
`creator` and `createdTime` removed from Scheduled Job after it was updated.

It causes missing audit log and exception during modify 
```
Audit log failed
java.lang.NullPointerException: null
	at com.enonic.xp.impl.scheduler.ScheduleAuditLogSupportImpl.addResult(ScheduleAuditLogSupportImpl.java:152)
	at com.enonic.xp.impl.scheduler.ScheduleAuditLogSupportImpl.doUpdate(ScheduleAuditLogSupportImpl.java:87)
	at com.enonic.xp.impl.scheduler.ScheduleAuditLogSupportImpl.lambda$modify$2(ScheduleAuditLogSupportImpl.java:77)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by rymsha** [comment]
Fix is to copy those _fileds_ from a job to be modified.

Since versions 7.7.0 to 7.7.2 could have jobs without creator - add a null check into audit log serializer.
