### ISSUE TITLE
Localise content when restoring in layer's archive

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp#9113]
Currently when there are items in a layer's archive, the sync job will fail almost immediately.
We should localise content when it's restored directly in the layer archive, so that sync job is not trying to recreate it in the archive after restore.

```
08:57:28.768 ERROR com.enonic.xp.impl.task.TaskRunnable - Error executing task [b4b614fd-396a-42dd-8243-3b5de9c23e60] 'Sync all projects': Node 38d36fd3-be0c-48a4-afc8-2aa8c83c9f0c already exists
com.enonic.xp.node.NodeIdExistsException: Node 38d36fd3-be0c-48a4-afc8-2aa8c83c9f0c already exists
	at com.enonic.xp.repo.impl.node.CreateNodeCommand.verifyNotExistsAlready(CreateNodeCommand.java:211)
	at com.enonic.xp.context.ContextImpl.runWith(ContextImpl.java:84)
	at com.enonic.xp.repo.impl.node.NodeHelper.runAsAdmin(NodeHelper.java:15)
	at com.enonic.xp.repo.impl.node.CreateNodeCommand.execute(CreateNodeCommand.java:67)
	at com.enonic.xp.repo.impl.node.ImportNodeCommand.createNode(ImportNodeCommand.java:117)
	at com.enonic.xp.repo.impl.node.ImportNodeCommand.execute(ImportNodeCommand.java:57)
	at com.enonic.xp.repo.impl.node.NodeServiceImpl.importNode(NodeServiceImpl.java:1009)
	at com.enonic.xp.core.impl.content.ImportContentCommand.doExecute(ImportContentCommand.java:52)
	at com.enonic.xp.core.impl.content.ImportContentCommand.execute(ImportContentCommand.java:33)
	at com.enonic.xp.core.impl.content.ContentServiceImpl.importContent(ContentServiceImpl.java:1296)
	at com.enonic.xp.core.impl.content.CreatedEventSyncCommand.syncChildContent(CreatedEventSyncCommand.java:80)
	at com.enonic.xp.core.impl.content.CreatedEventSyncCommand.lambda$doSync$0(CreatedEventSyncCommand.java:54)
	at com.enonic.xp.context.ContextImpl.runWith(ContextImpl.java:84)
	at com.enonic.xp.core.impl.content.CreatedEventSyncCommand.lambda$doSync$1(CreatedEventSyncCommand.java:47)
	at com.enonic.xp.context.ContextImpl.runWith(ContextImpl.java:84)
	at com.enonic.xp.core.impl.content.CreatedEventSyncCommand.doSync(CreatedEventSyncCommand.java:43)
	at com.enonic.xp.context.ContextImpl.runWith(ContextImpl.java:84)
	at com.enonic.xp.core.impl.content.AbstractContentEventSyncCommand.sync(AbstractContentEventSyncCommand.java:23)
	at java.base/java.lang.Iterable.forEach(Unknown Source)
	at com.enonic.xp.core.impl.content.ParentContentSynchronizer.lambda$doSync$17(ParentContentSynchronizer.java:232)
	at com.enonic.xp.context.ContextImpl.runWith(ContextImpl.java:84)
	at com.enonic.xp.core.impl.content.ParentContentSynchronizer.doSync(ParentContentSynchronizer.java:216)
	at com.enonic.xp.core.impl.content.ParentContentSynchronizer.lambda$doSyncWithChildren$14(ParentContentSynchronizer.java:188)
	at com.enonic.xp.context.ContextImpl.runWith(ContextImpl.java:84)
	at com.enonic.xp.core.impl.content.ParentContentSynchronizer.doSyncWithChildren(ParentContentSynchronizer.java:164)
	at com.enonic.xp.core.impl.content.ParentContentSynchronizer.lambda$sync$8(ParentContentSynchronizer.java:90)
	at java.base/java.util.Map.forEach(Unknown Source)
	at com.enonic.xp.core.impl.content.ParentContentSynchronizer.sync(ParentContentSynchronizer.java:89)
	at com.enonic.xp.core.impl.content.ProjectSyncCommand.execute(ProjectSyncCommand.java:36)
	at com.enonic.xp.core.impl.content.SyncContentServiceImpl.syncProject(SyncContentServiceImpl.java:85)
	at com.enonic.xp.app.contentstudio.rest.resource.content.task.ProjectsSyncTask.doSync(ProjectsSyncTask.java:50)
```

**Comment by sigdestad** [comment]
So - what did we end up localizing in this case? path? content?
