### ISSUE TITLE
Archive Restore: errors on backend for multple items

### ISSUE THREAD

**Issue by ashklianko** [enonic/xp#9246]
I reproduce it in Archive locally by restoring Features or it's copy: first expanding Features and then selecting all available items in it, then restoring.
![image.png](https://images.zenhubusercontent.com/58a588dc51aa2c3057749dad/3d796613-e2e7-4d82-a085-f148a984aa46)
Then I get error notification and problems in console:
```
java.lang.IllegalArgumentException: targetContent must be set.
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:141)
        at com.enonic.xp.core.impl.content.UpdatedEventSyncCommand$Builder.validate(UpdatedEventSyncCommand.java:193)
        at com.enonic.xp.core.impl.content.UpdatedEventSyncCommand$Builder.build(UpdatedEventSyncCommand.java:199)
        at com.enonic.xp.core.impl.content.ParentContentSynchronizer.lambda$new$5(ParentContentSynchronizer.java:72)
        at com.enonic.xp.core.impl.content.ParentContentSynchronizer.createEventCommand(ParentContentSynchronizer.java:305)
        at com.enonic.xp.core.impl.content.ParentContentSynchronizer.sync(ParentContentSynchronizer.java:188)
        at com.enonic.xp.core.impl.content.ProjectContentEventListener.lambda$doHandleContentEvent$12(ProjectContentEventListener.java:178)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
        at com.enonic.xp.core.impl.content.ProjectContentEventListener.lambda$doHandleContentEvent$15(ProjectContentEventListener.java:139)
        at com.enonic.xp.context.ContextImpl.runWith(ContextImpl.java:84)
        at com.enonic.xp.core.impl.content.ProjectContentEventListener.doHandleContentEvent(ProjectContentEventListener.java:102)
        at com.enonic.xp.core.impl.content.ProjectContentEventListener.lambda$handleContentEvent$4(ProjectContentEventListener.java:89)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by ashklianko** [comment]
Tested with @vbradnitski , works without errors on previous versions of studio-plus, breaks on current. Will be checking studio-plus

**Comment by ashklianko** [comment]
Issue moved to [enonic/app-contentstudio-plus #335](https://github.com/enonic/app-contentstudio-plus/issues/335) via [**ZenHub**](https://www.zenhub.com/)
