### ISSUE TITLE
Hazelcast throws exception for Node that has left the cluster.

### ISSUE THREAD

**Issue by jsi** [enonic/xp#9368]
It seems somewhat strange that we get an exception for a node that has left a cluster in a controlled manner.

```2022-02-16 12:16:06,193 ERROR c.e.x.i.s.distributed.RescheduleTask - Problem during tasks scheduling
com.hazelcast.core.HazelcastException: com.hazelcast.core.MemberLeftException: Member [10.223.4.47]:5701 - ec4afde4-97f6-46ed-bd53-360f7300758c has left cluster!
	at com.hazelcast.util.ExceptionUtil$1.create(ExceptionUtil.java:43)
	at com.hazelcast.util.ExceptionUtil$1.create(ExceptionUtil.java:37)
	at com.hazelcast.util.ExceptionUtil.peel(ExceptionUtil.java:121)
	at com.hazelcast.util.ExceptionUtil.peel(ExceptionUtil.java:72)
	at com.hazelcast.util.ExceptionUtil.rethrow(ExceptionUtil.java:134)
	at com.hazelcast.scheduledexecutor.impl.ScheduledExecutorServiceProxy.retrieveAllMemberOwnedScheduled(ScheduledExecutorServiceProxy.java:334)
	at com.hazelcast.scheduledexecutor.impl.ScheduledExecutorServiceProxy.getAllScheduledFutures(ScheduledExecutorServiceProxy.java:307)
	at com.enonic.xp.impl.scheduler.ClusteredSystemScheduler.disposeAllDone(ClusteredSystemScheduler.java:65)
	at com.enonic.xp.impl.scheduler.SchedulerExecutorServiceImpl.disposeAllDone(SchedulerExecutorServiceImpl.java:41)
	at com.enonic.xp.impl.scheduler.distributed.RescheduleTask.lambda$doRun$1(RescheduleTask.java:72)
	at com.enonic.xp.core.internal.osgi.OsgiSupport.withServiceOrElseGet(OsgiSupport.java:68)
	at com.enonic.xp.core.internal.osgi.OsgiSupport.withService(OsgiSupport.java:96)
	at com.enonic.xp.impl.scheduler.distributed.RescheduleTask.doRun(RescheduleTask.java:71)
	at com.enonic.xp.impl.scheduler.distributed.RescheduleTask.run(RescheduleTask.java:47)
	at com.hazelcast.scheduledexecutor.impl.ScheduledRunnableAdapter.call(ScheduledRunnableAdapter.java:56)
	at com.hazelcast.scheduledexecutor.impl.TaskRunner.call(TaskRunner.java:63)
	at com.hazelcast.scheduledexecutor.impl.TaskRunner.run(TaskRunner.java:80)
	at com.hazelcast.spi.impl.executionservice.impl.DelegateAndSkipOnConcurrentExecutionDecorator$DelegateDecorator.run(DelegateAndSkipOnConcurrentExecutionDecorator.java:77)
	at com.hazelcast.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:227)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by rymsha** [comment]
This is not something that causes problems. Just a stacktrace in logs.
