### ISSUE TITLE
500 error when accessing non-existent repository

### ISSUE THREAD

**Issue by rymsha** [enonic/xp#9432]
When attempting to access non-existing repo directly, this causes nasty 500 error, but should have returned a nice 404:
 I.e. http://localhost:8080/site/next/draft/hmdb -> 500 D'oh
 2022-04-12 20:18:55,893 ERROR c.e.x.p.i.e.ExceptionRendererImpl - Repository with id [com.enonic.cms.next] not found
 com.enonic.xp.web.WebException: Repository with id [com.enonic.cms.next] not found
     at com.enonic.xp.web.impl.exception.ExceptionMapperImpl.map(ExceptionMapperImpl.java:33)
     at com.enonic.xp.portal.handler.BasePortalHandler.handleError(BasePortalHandler.java:60)

**Comment by rymsha** [comment]
Check what happens when branch is not correct either.

**Comment by rymsha** [comment]
Expected result is 404
