### ISSUE TITLE
Access denied error appears after user logs in with a layer role 

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp#9642]
1. Create an user with `Admin Console login` role.
2. Create a project, then create a layer in this project
3. Open the layer and add Contributor or Owner role for this user.

![image](https://user-images.githubusercontent.com/3728712/184855899-f1486daa-0b0c-4051-b887-5ed87f3eff89.png)

4. Do login with the user.

BUG - notifation error appears after the user is logged in
![image](https://user-images.githubusercontent.com/3728712/184853207-7a0d9e09-ea05-4cf7-8a7b-caa219d7f076.png)

```
com.enonic.xp.exception.ForbiddenAccessException: Access denied to user [user:system:layer-contributor150824] ''layer-contributor150824''
        at com.enonic.xp.repo.impl.repository.RepositoryServiceImpl.requireAdminRole(RepositoryServiceImpl.java:314)
        at com.enonic.xp.repo.impl.repository.RepositoryServiceImpl.get(RepositoryServiceImpl.java:212)
        at com.enonic.xp.core.impl.project.ProjectServiceImpl.doGet(ProjectServiceImpl.java:380)
        at com.enonic.xp.core.impl.project.ProjectServiceImpl.doGetParents(ProjectServiceImpl.java:357)
        at com.enonic.xp.core.impl.project.ProjectServiceImpl.doGraph(ProjectServiceImpl.java:329)
        at com.enonic.xp.core.impl.project.ProjectServiceImpl.graph(ProjectServiceImpl.java:307)
        at com.enonic.xp.app.contentstudio.rest.resource.project.ProjectResource.getTree(ProjectResource.java:214)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
        at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
        at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestCon
com.enonic.xp.exception.ForbiddenAccessException: Access denied to user [user:system:layer-contributor150824] ''layer-contributor150824''
        at com.enonic.xp.repo.impl.repository.RepositoryServiceImpl.requireAdminRole(RepositoryServiceImpl.java:314)
        at com.enonic.xp.repo.impl.repository.RepositoryServiceImpl.get(RepositoryServiceImpl.java:212)
        at com.enonic.xp.core.impl.project.ProjectServiceImpl.doGet(ProjectServiceImpl.java:380)
        at com.enonic.xp.core.impl.project.ProjectServiceImpl.doGetParents(ProjectServiceImpl.java:357)
        at com.enonic.xp.core.impl.project.ProjectServiceImpl.doGraph(ProjectServiceImpl.java:329)
        at com.enonic.xp.core.impl.project.ProjectServiceImpl.graph(ProjectServiceImpl.java:307)
        at com.enonic.xp.app.contentstudio.rest.resource.project.ProjectResource.getTree(ProjectResource.java:214)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
        at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
        at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestConcom.enonic.xp.exception.ForbiddenAccessException: Access denied to user [user:system:layer-contributor150824] ''layer-contributor150824''
        at com.enonic.xp.repo.impl.repository.RepositoryServiceImpl.requireAdminRole(RepositoryServiceImpl.java:314)
        at com.enonic.xp.repo.impl.repository.RepositoryServiceImpl.get(RepositoryServiceImpl.java:212)
        at com.enonic.xp.core.impl.project.ProjectServiceImpl.doGet(ProjectServiceImpl.java:380)
        at com.enonic.xp.core.impl.project.ProjectServiceImpl.doGetParents(ProjectServiceImpl.java:357)
        at com.enonic.xp.core.impl.project.ProjectServiceImpl.doGraph(ProjectServiceImpl.java:329)
        at com.enonic.xp.core.impl.project.ProjectServiceImpl.graph(ProjectServiceImpl.java:307)
        at com.enonic.xp.app.contentstudio.rest.resource.project.ProjectResource.getTree(ProjectResource.java:214)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
        at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
        at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestCon

**Comment by ashklianko** [comment]
This issue appeared after merging epic-schema to master branch, changes in `ProjectServiceImpl.java` in `doGraph()`:
```
        Stream.concat( Lists.reverse( doGetParents( targetProject ) ).stream(), Stream.of( targetProject ) )
            .forEach( p -> graph.add( ProjectGraphEntry.create().name( p.getName() ).parent( p.getParent() ).build() ) );
```

`doGetParents()` is being called without a context so if user doesn't have enough persmission it fails
