### ISSUE TITLE
Blob files may appear empty

### ISSUE THREAD

**Issue by rymsha** [enonic/xp#9651]
It is a rare condition, happens on audit log, but nodes can't be loaded after it happens

```
Caused by: java.lang.RuntimeException: Failed to load blobs with keys: a97613ded1c7658f63cb5653afe0ad4f520e1a64, 68b9a2d838fe2258594d9704eec226313d95edd0, 6be8a7d65abaa1a4ca3434b279bd58e547ea8cb6
        at com.enonic.xp.repo.impl.node.dao.NodeVersionServiceImpl.getFromBlob(NodeVersionServiceImpl.java:125)
        at com.enonic.xp.repo.impl.node.dao.NodeVersionServiceImpl.doGetNodeVersion(NodeVersionServiceImpl.java:77)
        at com.enonic.xp.repo.impl.node.dao.NodeVersionServiceImpl.get(NodeVersionServiceImpl.java:60)
        at com.enonic.xp.repo.impl.storage.NodeStorageServiceImpl.doGetNode(NodeStorageServiceImpl.java:470)
        at com.enonic.xp.repo.impl.storage.NodeStorageServiceImpl.get(NodeStorageServiceImpl.java:299)
        at com.enonic.xp.repo.impl.node.GetNodeByIdCommand.execute(GetNodeByIdCommand.java:26)
        at com.enonic.xp.repo.impl.node.NodeServiceImpl.doGetById(NodeServiceImpl.java:187)
        at com.enonic.xp.repo.impl.node.NodeServiceImpl.executeGetById(NodeServiceImpl.java:154)
        at com.enonic.xp.repo.impl.node.NodeServiceImpl.getById(NodeServiceImpl.java:122)
        at com.enonic.xp.repo.impl.vacuum.versiontable.VersionTableVacuumCommand.lambda$findVersionsInBranches$5(VersionTableVacuumCommand.java:226)
        at com.enonic.xp.context.ContextImpl.callWith(ContextImpl.java:102)
        at com.enonic.xp.repo.impl.vacuum.versiontable.VersionTableVacuumCommand.findVersionsInBranches(VersionTableVacuumCommand.java:226)
        at com.enonic.xp.repo.impl.vacuum.versiontable.VersionTableVacuumCommand.processVersion(VersionTableVacuumCommand.java:194)
        at com.enonic.xp.repo.impl.vacuum.versiontable.VersionTableVacuumCommand.doProcessRepository(VersionTableVacuumCommand.java:133)
        at com.enonic.xp.repo.impl.vacuum.versiontable.VersionTableVacuumCommand.lambda$processRepository$0(VersionTableVacuumCommand.java:103)
        at com.enonic.xp.context.ContextImpl.runWith(ContextImpl.java:86)
        at com.enonic.xp.repo.impl.vacuum.versiontable.VersionTableVacuumCommand.processRepository(VersionTableVacuumCommand.java:103)
        at java.base/java.lang.Iterable.forEach(Unknown Source)
        at com.enonic.xp.repo.impl.vacuum.versiontable.VersionTableVacuumCommand.execute(VersionTableVacuumCommand.java:93)
        at com.enonic.xp.repo.impl.vacuum.versiontable.VersionTableVacuumTask.execute(VersionTableVacuumTask.java:43)
        at com.enonic.xp.repo.impl.vacuum.VacuumServiceImpl.doVacuum(VacuumServiceImpl.java:67)
        at com.enonic.xp.repo.impl.vacuum.VacuumServiceImpl.vacuum(VacuumServiceImpl.java:44)
        at com.enonic.xp.app.system.VacuumTaskHandler.execute(VacuumTaskHandler.java:35)
        at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$3517$196A$vacuum/0x00000008022fa040.L:1#run(com.enonic.xp.app.system:/tasks/vacuum/vacuum.js:15)
        at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(Unknown Source)
        at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptFunction.invoke(Unknown Source)
        at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptRuntime.apply(Unknown Source)
        at jdk.scripting.nashorn/jdk.nashorn.api.scripting.ScriptObjectMirror.call(Unknown Source)
        at com.enonic.xp.script.impl.value.FunctionScriptValue.call(FunctionScriptValue.java:36)
        ... 12 common frames omitted
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
 at [Source: (byte[])""; line: 1, column: 0]
        at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
        at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4688)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4586)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3609)
        at com.enonic.xp.repo.impl.node.json.NodeVersionJsonSerializer.toNodeVersion(NodeVersionJsonSerializer.java:62)
        at com.enonic.xp.repo.impl.node.dao.NodeVersionServiceImpl.getFromBlob(NodeVersionServiceImpl.java:113)
        ... 40 common frames omitted
```

Checking files size gives us a hint - `a97613ded1c7658f63cb5653afe0ad4f520e1a64` file is empty!

**Comment by rymsha** [comment]
It doesn't appear often,  and it looks more like rsync or restore from backup done improperly
