### ISSUE TITLE
Testing library fails to load node library

### ISSUE THREAD

**Issue by edloidas** [enonic/xp#9960]
If you run a JS code (vanilla or compiled, doesn't matter) from your Java test using testing library (`com.enonic.xp.testing`) AND require node lib `var nodeLib = require('/lib/xp/node');` the test will fail with the following error:
```
Service [com.enonic.xp.node.NodeService] not found
com.enonic.xp.resource.ResourceProblemException: Service [com.enonic.xp.node.NodeService] not found
	at app//com.enonic.xp.resource.ResourceProblemException$Builder.build(ResourceProblemException.java:131)
	at app//com.enonic.xp.script.impl.util.ErrorHelper.doHandleException(ErrorHelper.java:54)
	at app//com.enonic.xp.script.impl.util.ErrorHelper.handleError(ErrorHelper.java:27)
        ...
```
Other libraries work just fine.

---

The sample Java test file:
```java
package com.enonic.example.test;

import org.junit.Test;

import com.enonic.xp.testing.ScriptTestSupport;

public class NodeTest
        extends ScriptTestSupport {

    @Test
    public void testNodeLib() {
        runFunction("/com/enonic/cloud/api/util/node-test.js", "runNodeLibFunc");
    }
}
```

Sample JS file
**node-test.js**
```js
const t = require('/lib/xp/testing');
const node = require('/lib/xp/node');

function runNodeLibFunc() {
    t.assertEquals('foo', 'foo');
}

module.exports = {
    runNodeLibFunc,
};
```

**Comment by rymsha** [comment]
By default `ScriptTestSupport` registers mocks `ContentService` and `ProjectService` only. They are "empty", so this practice is not very useful. Instead `ScriptTestSupport` should be used like: 

```
public class NodeTest
    extends ScriptTestSupport
{
    private NodeService nodeService;

    @Override
    public void initialize()
        throws Exception
    {
        super.initialize();
        this.nodeService = Mockito.mock( NodeService.class );
        addService( NodeService.class, this.nodeService );
    }

    @Test
    public void testExamples()
    {

        Mockito.when( nodeService.getById( Mockito.any() )).thenReturn( Mockito.mock( Node.class ) );

        runScript( "/lib/xp/examples/auth/findUsers.js" );
    }
}


```

**Comment by rymsha** [comment]
There is also a way to mock libs directly in JS. https://developer.enonic.com/docs/writing-unit-tests#mocking_services
